use super::assets::{
    VIEWER_CSS, VIEWER_DRAG_JS, VIEWER_DYNAMICS_JS, VIEWER_JS, VIEWER_RENDER_JS, VIEWER_SCENE_JS,
    indent_asset, van_runtime_to_global,
};
use super::render_scene_json;
use crate::runtime::scene::Scene;
use std::fmt::Write as _;

pub(super) fn render_standalone_html_document(scene: &Scene, width: u32, height: u32) -> String {
    let mut html = String::new();
    let scene_json = render_scene_json(scene, width, height, false);
    let van_js = van_runtime_to_global();
    let viewer_modules_js =
        format!("{VIEWER_SCENE_JS}\n{VIEWER_RENDER_JS}\n{VIEWER_DRAG_JS}\n{VIEWER_DYNAMICS_JS}");
    let frame_width = width + 40;
    let shape_count = scene.images.len()
        + scene.lines.len()
        + scene.polygons.len()
        + scene.circles.len()
        + scene.arcs.len()
        + scene.labels.len();
    let _ = write!(
        html,
        r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>gsp-rs export</title>
  <style>
    :root {{
      --frame-width: {frame_width}px;
    }}
{embedded_css}
  </style>
</head>
<body>
  <main>
    <div class="frame">
        <div class="toolbar">
        <div class="controls">
          <button id="reset-view" type="button">Reset View</button>
          <button id="toggle-debug" type="button" aria-expanded="false">Debug</button>
          <div id="parameter-controls"></div>
        </div>
        <span class="hint">Drag a point to edit, drag empty space to pan, wheel to zoom</span>
      </div>
      <div class="canvas-shell">
        <canvas id="view" width="{width}" height="{height}"></canvas>
        <div id="button-overlays"></div>
      </div>
      <section id="debug-panel" class="debug-panel" hidden>
        <div class="debug-toolbar">
          <strong>Hierarchy Debug</strong>
          <div class="debug-actions">
            <button id="debug-tab-graph" type="button" data-debug-tab="graph" aria-pressed="true">Graph</button>
            <button id="debug-tab-json" type="button" data-debug-tab="json" aria-pressed="false">JSON</button>
            <button id="debug-dump-console" type="button">Dump Console</button>
          </div>
        </div>
        <pre id="debug-output" class="debug-output"></pre>
      </section>
      <div class="meta">
        <span>Generated by gsp-rs</span>
        <span>{shape_count} shapes</span>
        <div class="right">
          <span id="coord-readout">x -, y -</span>
          <span id="zoom-readout">zoom 100%</span>
        </div>
      </div>
    </div>
  </main>
  <script id="scene-data" type="application/json">{scene_json}</script>
  <script>
{embedded_van_js}
  </script>
  <script>
{embedded_viewer_modules_js}
  </script>
  <script>
{embedded_js}
  </script>
</body>
</html>
"#,
        width = width,
        height = height,
        frame_width = frame_width,
        shape_count = shape_count,
        scene_json = scene_json,
        embedded_css = indent_asset(VIEWER_CSS, 4),
        embedded_van_js = indent_asset(&van_js, 4),
        embedded_viewer_modules_js = indent_asset(&viewer_modules_js, 4),
        embedded_js = indent_asset(VIEWER_JS, 4),
    );
    html
}
