use super::assets::{
    VIEWER_CSS, VIEWER_RUNTIME_JS, indent_asset, minify_css_asset, van_runtime_to_global,
};
use super::render_scene_json;
use crate::runtime::scene::Scene;
use std::fmt::Write as _;

pub(crate) struct StandaloneHtmlPage<'a> {
    pub(crate) title: &'a str,
    pub(crate) scene: &'a Scene,
    pub(crate) width: u32,
    pub(crate) height: u32,
    pub(crate) document_layout: bool,
}

pub(super) fn render_standalone_html_pages(pages: &[StandaloneHtmlPage<'_>]) -> String {
    let first_page = pages
        .first()
        .expect("standalone html export requires at least one page");
    let width = first_page.width;
    let height = first_page.height;
    let document_layout = pages.iter().any(|page| page.document_layout);
    let mut html = String::new();
    let scene_json = render_document_scene_json(pages);
    let van_js = van_runtime_to_global();
    let canvas_shell_class = if document_layout {
        "canvas-shell is-document-layout"
    } else {
        "canvas-shell"
    };
    let canvas_stage_class = if document_layout {
        "canvas-stage is-document-layout"
    } else {
        "canvas-stage"
    };
    let shape_count = pages
        .iter()
        .map(|page| shape_count(page.scene))
        .sum::<usize>();
    let page_tabs = render_page_tabs(pages);
    let app_shell_class = if pages.len() > 1 {
        "app-shell has-page-tabs"
    } else {
        "app-shell"
    };
    let _ = write!(
        html,
        r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>gsp-rs export</title>
  <style>
    :root {{
      --scene-width: {width};
      --scene-height: {height};
    }}
{embedded_css}
  </style>
</head>
<body>
  <main>
    <div id="viewer-shell" class="{app_shell_class}">
      <div class="toolbar">
        <div class="controls">
          <button id="reset-view" type="button">Reset View</button>
          <button id="toggle-fullscreen" type="button" aria-pressed="false">全屏</button>
          <button id="toggle-debug" type="button" aria-expanded="false">Debug</button>
          <div id="parameter-controls"></div>
        </div>
        <span class="hint">Drag a point to edit, drag empty space to pan, wheel to zoom</span>
      </div>
      {page_tabs}
      <div class="{canvas_shell_class}">
        <div class="{canvas_stage_class}">
          <svg id="view" viewBox="0 0 {width} {height}" width="{width}" height="{height}" aria-label="GSP viewer">
            <g id="grid-layer"></g>
            <g id="scene-layer"></g>
            <g id="measure-layer" aria-hidden="true" opacity="0">
              <text id="measure-text"></text>
            </g>
          </svg>
          <div id="button-overlays"></div>
        </div>
      </div>
      <section id="debug-panel" class="debug-panel" hidden>
        <div class="debug-toolbar">
          <strong>Payload Debug</strong>
          <div class="debug-actions">
            <button id="debug-tab-selection" type="button" data-debug-tab="selection" aria-pressed="true">Selection</button>
            <button id="debug-tab-scene" type="button" data-debug-tab="scene" aria-pressed="false">Scene</button>
            <button id="debug-tab-json" type="button" data-debug-tab="json" aria-pressed="false">JSON</button>
            <button id="debug-dump-console" type="button">Dump Console</button>
          </div>
        </div>
        <pre id="debug-output" class="debug-output"></pre>
      </section>
      <div class="meta">
        <span>Generated by gsp-rs</span>
        <span>{shape_count} shapes</span>
        <div class="right">
          <span id="coord-readout">x -, y -</span>
          <span id="zoom-readout">zoom 100%</span>
        </div>
      </div>
    </div>
  </main>
  <script id="scene-data" type="application/json">{scene_json}</script>
  <!-- viewer-runtime: full -->
  <script>
{embedded_van_js}
  </script>
  <script>
{embedded_viewer_runtime_js}
  </script>
</body>
</html>
"#,
        width = width,
        height = height,
        app_shell_class = app_shell_class,
        canvas_shell_class = canvas_shell_class,
        canvas_stage_class = canvas_stage_class,
        shape_count = shape_count,
        page_tabs = page_tabs,
        scene_json = scene_json,
        embedded_css = minify_css_asset(VIEWER_CSS),
        embedded_van_js = indent_asset(&van_js, 4),
        embedded_viewer_runtime_js = indent_asset(VIEWER_RUNTIME_JS, 4),
    );
    html
}

pub(crate) fn render_document_scene_json(pages: &[StandaloneHtmlPage<'_>]) -> String {
    if pages.len() == 1 {
        let page = &pages[0];
        return render_scene_json(page.scene, page.width, page.height, false);
    }

    let mut json = String::from(r#"{"kind":"gsp-document","pages":["#);
    for (index, page) in pages.iter().enumerate() {
        if index > 0 {
            json.push(',');
        }
        let title = serde_json::to_string(page.title).expect("page title should serialize");
        let scene_json = render_scene_json(page.scene, page.width, page.height, false);
        let _ = write!(
            json,
            r#"{{"index":{index},"title":{title},"scene":{scene_json}}}"#,
        );
    }
    json.push_str("]}");
    json
}

fn render_page_tabs(pages: &[StandaloneHtmlPage<'_>]) -> String {
    if pages.len() <= 1 {
        return String::new();
    }

    let mut html = String::from(r#"<div id="page-tabs" class="page-tabs" role="tablist">"#);
    for (index, page) in pages.iter().enumerate() {
        let selected = if index == 0 { "true" } else { "false" };
        let active_class = if index == 0 { " is-active" } else { "" };
        let title = html_escape(page.title);
        let _ = write!(
            html,
            r#"<button type="button" class="page-tab{active_class}" role="tab" aria-selected="{selected}" data-page-index="{index}">{title}</button>"#,
        );
    }
    html.push_str("</div>");
    html
}

fn html_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn shape_count(scene: &Scene) -> usize {
    scene.images.len()
        + scene.lines.len()
        + scene.polygons.len()
        + scene.circles.len()
        + scene.arcs.len()
        + scene.labels.len()
}

#[cfg(test)]
mod tests {
    use super::{StandaloneHtmlPage, render_standalone_html_pages};
    use crate::runtime::{geometry::Bounds, scene::Scene};

    fn empty_scene() -> Scene {
        Scene {
            graph_mode: false,
            pi_mode: false,
            saved_viewport: false,
            y_up: false,
            origin: None,
            bounds: Bounds {
                min_x: 0.0,
                max_x: 1.0,
                min_y: 0.0,
                max_y: 1.0,
            },
            images: Vec::new(),
            lines: Vec::new(),
            polygons: Vec::new(),
            circles: Vec::new(),
            arcs: Vec::new(),
            labels: Vec::new(),
            points: Vec::new(),
            point_iterations: Vec::new(),
            circle_iterations: Vec::new(),
            line_iterations: Vec::new(),
            polygon_iterations: Vec::new(),
            label_iterations: Vec::new(),
            iteration_tables: Vec::new(),
            buttons: Vec::new(),
            parameters: Vec::new(),
            functions: Vec::new(),
            function_definitions: Vec::new(),
        }
    }

    #[test]
    fn standalone_html_always_embeds_full_runtime() {
        let scene = empty_scene();
        let html = render_standalone_html_pages(&[StandaloneHtmlPage {
            title: "empty",
            scene: &scene,
            width: 640,
            height: 480,
            document_layout: false,
        }]);

        assert!(html.contains("<!-- viewer-runtime: full -->"));
        assert!(html.contains("function lineLikeAllowsParam"));
        assert!(html.contains("function dependencyRootsForDraggedPoint"));
        assert!(html.contains("function isVisibilityButtonAction"));
        assert!(!html.contains("viewer-runtime: scene="));
    }
}
