use super::*;

#[test]
fn compiles_fixture_into_standalone_html() {
    let html = fixture_html(
        include_bytes!("../../../tests/fixtures/gsp/static/point.gsp"),
        "fixture should compile",
    );

    assert!(html.contains("<!doctype html>"));
    assert!(html.contains("<svg id=\"view\""));
    assert!(html.contains("Generated by gsp-rs"));
    assert!(html.contains("application/json"));
    assert!(html.contains("toggle-debug"));
    assert!(html.contains("window.gspDebug"));
}

#[test]
fn standalone_html_keeps_framed_default_and_includes_fullscreen_toggle() {
    let html = fixture_html(
        include_bytes!("../../../tests/fixtures/gsp/static/point.gsp"),
        "fixture should compile",
    );

    assert!(html.contains("<main>"));
    assert!(html.contains("<div id=\"viewer-shell\" class=\"app-shell\">"));
    assert!(html.contains("id=\"toggle-fullscreen\""));
    assert!(html.contains(">全屏</button>"));
    assert!(html.contains("--scene-width: 1637;"));
    assert!(html.contains("--scene-height: 841;"));
    assert!(html.contains(
        ".app-shell{width:100%;margin:0 auto;display:grid;min-height:calc(100dvh - 40px);"
    ));
    assert!(html.contains(".app-shell:fullscreen{width:100vw;height:100dvh;"));
    assert!(
        html.contains("document.addEventListener(\"fullscreenchange\", syncFullscreenButton);")
    );
    assert!(
        html.contains("viewerShell.requestFullscreen?.()"),
        "fullscreen button should invoke the fullscreen api"
    );
}

#[test]
fn svg_runtime_keeps_geometry_and_grid_layers_inside_the_same_stage() {
    let html = fixture_html(
        include_bytes!("../../../tests/fixtures/gsp/static/point.gsp"),
        "fixture should compile",
    );

    assert!(html.contains("<g id=\"grid-layer\"></g>"));
    assert!(html.contains("<g id=\"scene-layer\"></g>"));
    assert!(html.contains("viewBox=\"0 0 1637 841\""));
}

#[test]
fn multipage_fixture_exports_one_html_document_with_page_tabs() {
    let html = fixture_html(
        include_bytes!("../../../tests/fixtures/bug/迭代方法2(蚂蚁).gsp"),
        "multipage fixture should compile",
    );

    assert!(html.contains("class=\"app-shell has-page-tabs\""));
    assert!(html.contains("id=\"page-tabs\""));
    assert!(html.contains("data-page-index=\"0\""));
    assert!(html.contains("data-page-index=\"1\""));
    assert!(html.contains("\"kind\":\"gsp-document\""));
    assert!(html.contains("\"title\":\"Page 1\""));
    assert!(html.contains("\"title\":\"Page 2\""));
}

#[test]
fn multipage_scene_json_preserves_every_page_and_document_dimensions() {
    let scene = fixture_scene(
        include_bytes!("../../../tests/fixtures/bug/迭代方法2(蚂蚁).gsp"),
        "multipage fixture should compile",
    );
    assert_eq!(scene["kind"].as_str(), Some("gsp-document"));
    let pages = scene["pages"].as_array().expect("document pages");
    assert_eq!(pages.len(), 2);
    let first_width = pages[0]["scene"]["width"].as_u64();
    let first_height = pages[0]["scene"]["height"].as_u64();
    assert!(first_width.is_some_and(|width| width != 800));
    assert!(first_height.is_some_and(|height| height != 600));
    assert_eq!(pages[1]["scene"]["width"].as_u64(), first_width);
    assert_eq!(pages[1]["scene"]["height"].as_u64(), first_height);
}

#[test]
fn compiles_fixture_and_also_writes_payload_log_and_debug_json() {
    let fixture = FixtureArtifacts::new(
        "payload-log-success",
        "point.gsp",
        include_bytes!("../../../tests/fixtures/gsp/static/point.gsp"),
    );

    let output = fixture.compile_standard_with_outputs();

    assert!(output.payload_log.contains("载荷说明"));
    assert!(output.payload_log.contains("问题数量: 0"));
    assert!(output.payload_log.contains("Construction VALUE"));
    assert!(
        output
            .payload_log
            .contains("{1} Point(323,217)[mediumPoint];")
    );

    assert!(output.debug_json.contains("\n  \"width\": 1637,"));
    assert!(output.debug_json.contains("\"points\": ["));
    assert_eq!(output.scene["width"].as_u64(), Some(1637));
}

#[test]
fn html_only_compile_writes_only_html() {
    let fixture = FixtureArtifacts::new(
        "html-only-success",
        "point.gsp",
        include_bytes!("../../../tests/fixtures/gsp/static/point.gsp"),
    );

    fixture.compile_html_only();

    assert!(
        fixture.paths.html_path.exists(),
        "expected html output to be written"
    );
    assert!(
        !fixture.paths.payload_log_path.exists(),
        "html-only compile should not emit a payload log"
    );
    assert!(
        !fixture.paths.debug_json_path.exists(),
        "html-only compile should not emit debug json"
    );
}

#[test]
fn exports_scene_json_for_console_debugging() {
    let scene_json = fixture_scene_json(
        include_bytes!("../../../tests/fixtures/gsp/static/point.gsp"),
        "fixture should compile",
    );

    assert!(scene_json.contains("\n  \"width\": 1637,"));
    assert!(scene_json.contains("\"points\": ["));
}

#[test]
fn snapshots_point_fixture_scene_json() {
    let scene_json = fixture_scene_json(
        include_bytes!("../../../tests/fixtures/gsp/static/point.gsp"),
        "fixture should compile",
    );

    assert_snapshot!("point_fixture_scene_json", scene_json);
}
