use std::{
    env, fs, io,
    path::{Path, PathBuf},
    process::{Command, ExitCode},
};

use oxc_allocator::Allocator;
use oxc_codegen::{Codegen, CodegenOptions, CodegenReturn};
use oxc_data_structures::code_buffer::IndentChar;
use oxc_parser::Parser;
use oxc_semantic::SemanticBuilder;
use oxc_span::SourceType;
use oxc_transformer::{ESTarget, TransformOptions, Transformer};

const RUNTIME_SOURCES: &[&str] = &[
    "viewer_geometry",
    "viewer_scene_basic",
    "viewer_scene_circular",
    "viewer_scene_trace",
    "viewer_scene_intersections",
    "viewer_render_basic",
    "viewer_render_images",
    "viewer_render_polygons",
    "viewer_render_circular",
    "viewer_render_labels",
    "viewer_render_tables",
    "viewer_render_hotspots",
    "viewer_overlay",
    "viewer_drag",
    "viewer_dynamics",
    "viewer",
];

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("xtask: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = env::args().skip(1);
    match args.next().as_deref() {
        Some("runtime") => build_runtime(),
        Some("check-runtime") => {
            build_runtime()?;
            run_command(Command::new("npm").args(["run", "typecheck:js"]), repo_root())?;
            Ok(())
        }
        Some("build") => {
            build_runtime()?;
            let mut cargo_args = vec!["build".to_string()];
            cargo_args.extend(args);
            let mut command = Command::new("cargo");
            command.args(cargo_args);
            run_command(&mut command, repo_root())?;
            Ok(())
        }
        Some(command) => Err(format!("unknown xtask command `{command}`").into()),
        None => {
            eprintln!("usage: cargo xtask <runtime|check-runtime|build>");
            Ok(())
        }
    }
}

fn build_runtime() -> Result<(), Box<dyn std::error::Error>> {
    let root = repo_root();
    write_runtime_bundle(&root)?;
    Ok(())
}

fn write_runtime_bundle(root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let output_path = root.join("src/html/generated/viewer-runtime.js");
    let mut bundle = String::from(
        "// Generated by `cargo xtask runtime`. Do not edit by hand.\n\
         // Source files live in src/html/runtime/*.ts.\n\n",
    );
    for source in RUNTIME_SOURCES {
        let source_path = root.join(format!("src/html/runtime/{source}.ts"));
        let source_js = transpile_typescript(&source_path)?.replace("import(\"./generated/", "import(\"./");
        bundle.push_str("// ---- ");
        bundle.push_str(source);
        bundle.push_str(".ts ----\n");
        bundle.push_str(source_js.trim_end());
        bundle.push_str("\n\n");
    }
    fs::write(output_path, bundle)?;
    Ok(())
}

fn transpile_typescript(path: &Path) -> Result<String, Box<dyn std::error::Error>> {
    let source = fs::read_to_string(path)?;
    let allocator = Allocator::default();
    let source_type = SourceType::from_path(path)?.with_typescript(true);
    let parser_return = Parser::new(&allocator, &source, source_type).parse();
    if !parser_return.errors.is_empty() {
        return Err(format!(
            "failed to parse {}: {} diagnostic(s)",
            path.display(),
            parser_return.errors.len(),
        )
        .into());
    }

    let mut program = parser_return.program;
    let semantic = SemanticBuilder::new()
        .with_excess_capacity(2.0)
        .with_enum_eval(true)
        .build(&program);
    if !semantic.errors.is_empty() {
        return Err(format!(
            "failed to analyze {}: {} diagnostic(s)",
            path.display(),
            semantic.errors.len(),
        )
        .into());
    }

    let transform_options = TransformOptions::from(ESTarget::ES2021);
    let transformed = Transformer::new(&allocator, path, &transform_options)
        .build_with_scoping(semantic.semantic.into_scoping(), &mut program);
    if !transformed.errors.is_empty() {
        return Err(format!(
            "failed to transform {}: {} diagnostic(s)",
            path.display(),
            transformed.errors.len(),
        )
        .into());
    }

    let options = CodegenOptions {
        minify: false,
        indent_char: IndentChar::Space,
        indent_width: 2,
        ..CodegenOptions::default()
    };
    let CodegenReturn { code, .. } = Codegen::new().with_options(options).build(&program);
    Ok(code)
}

fn run_command(command: &mut Command, cwd: impl AsRef<Path>) -> io::Result<()> {
    let status = command.current_dir(cwd).status()?;
    if status.success() {
        return Ok(());
    }
    Err(io::Error::other(format!(
        "command failed with status {status}: {command:?}",
    )))
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask crate should live under repository root")
        .to_path_buf()
}
