use std::{
    env, fs, io,
    path::{Path, PathBuf},
    process::{Command, ExitCode},
};

const RUNTIME_SOURCES: &[&str] = &[
    "viewer_geometry",
    "viewer_scene_basic",
    "viewer_scene_circular",
    "viewer_scene_trace",
    "viewer_scene_intersections",
    "viewer_render_basic",
    "viewer_render_images",
    "viewer_render_polygons",
    "viewer_render_circular",
    "viewer_render_labels",
    "viewer_render_tables",
    "viewer_render_hotspots",
    "viewer_overlay",
    "viewer_drag",
    "viewer_dynamics",
    "viewer",
];

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("xtask: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = env::args().skip(1);
    match args.next().as_deref() {
        Some("runtime") => build_runtime(),
        Some("check-runtime") => {
            build_runtime()?;
            run_command(Command::new("npm").args(["run", "typecheck:js"]), repo_root())?;
            Ok(())
        }
        Some("build") => {
            build_runtime()?;
            let mut cargo_args = vec!["build".to_string()];
            cargo_args.extend(args);
            let mut command = Command::new("cargo");
            command.args(cargo_args);
            run_command(&mut command, repo_root())?;
            Ok(())
        }
        Some(command) => Err(format!("unknown xtask command `{command}`").into()),
        None => {
            eprintln!("usage: cargo xtask <runtime|check-runtime|build>");
            Ok(())
        }
    }
}

fn build_runtime() -> Result<(), Box<dyn std::error::Error>> {
    let root = repo_root();
    run_command(
        Command::new("cargo").args(["run", "--bin", "generate_viewer_types"]),
        &root,
    )?;
    run_command(
        Command::new("npm").args(["exec", "tsc", "--", "-p", "tsconfig.runtime.json"]),
        &root,
    )?;
    write_runtime_bundle(&root)?;
    Ok(())
}

fn write_runtime_bundle(root: &Path) -> io::Result<()> {
    let emit_dir = root.join("target/xtask/viewer-runtime");
    let output_path = root.join("src/html/generated/viewer-runtime.js");
    let mut bundle = String::from(
        "// Generated by `cargo xtask runtime`. Do not edit by hand.\n\
         // Source files live in src/html/runtime/*.ts.\n\
         // @ts-nocheck\n\n",
    );
    for source in RUNTIME_SOURCES {
        let source_path = emit_dir.join(format!("{source}.js"));
        let source_js = fs::read_to_string(&source_path)?
            .replace("import(\"./generated/", "import(\"./")
            .replace("// @ts-check\n", "")
            .replace("// @ts-nocheck\n", "");
        bundle.push_str("// ---- ");
        bundle.push_str(source);
        bundle.push_str(".ts ----\n");
        bundle.push_str(source_js.trim_end());
        bundle.push_str("\n\n");
    }
    fs::write(output_path, bundle)
}

fn run_command(command: &mut Command, cwd: impl AsRef<Path>) -> io::Result<()> {
    let status = command.current_dir(cwd).status()?;
    if status.success() {
        return Ok(());
    }
    Err(io::Error::other(format!(
        "command failed with status {status}: {command:?}",
    )))
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask crate should live under repository root")
        .to_path_buf()
}
