use crate::format::{GspFile, PointRecord};
use crate::render::{Scene, ScenePointConstraint, build_scene, darken};
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

pub fn render_points_to_html(
    file: &GspFile,
    output_path: &Path,
    width: u32,
    height: u32,
) -> Result<(), String> {
    if !matches!(
        output_path.extension().and_then(|ext| ext.to_str()),
        Some("html") | Some("HTML") | Some("htm") | Some("HTM")
    ) {
        return Err(format!(
            "html output path must end with .html or .htm: {}",
            output_path.display()
        ));
    }

    let scene = build_scene(file);
    let html = build_standalone_html(&scene, width, height);

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "failed to create html output directory {}: {error}",
                parent.display()
            )
        })?;
    }

    fs::write(output_path, html)
        .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    Ok(())
}

fn build_standalone_html(scene: &Scene, width: u32, height: u32) -> String {
    let mut html = String::new();
    let scene_json = scene_to_json(scene, width, height);
    let _ = write!(
        html,
        r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>gsp-rs export</title>
  <style>
    :root {{
      color-scheme: light;
      --paper: rgb(250, 250, 248);
      --frame: rgb(215, 215, 210);
      --ink: rgb(32, 32, 32);
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
      background:
        radial-gradient(circle at top, rgba(255,255,255,0.92), rgba(235,236,230,0.9)),
        linear-gradient(180deg, rgb(243, 244, 240), rgb(225, 227, 220));
      color: var(--ink);
      font: 14px/1.45 "Noto Sans", "Segoe UI", sans-serif;
    }}
    main {{
      width: min(100vw, {frame_width}px);
      padding: 20px;
    }}
    .frame {{
      background: rgba(255,255,255,0.72);
      border: 1px solid var(--frame);
      border-radius: 18px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.12);
      overflow: hidden;
      backdrop-filter: blur(8px);
    }}
    .toolbar {{
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 12px;
      padding: 10px 14px;
      border-bottom: 1px solid rgba(0,0,0,0.08);
      background: rgba(255,255,255,0.78);
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.04em;
    }}
    .toolbar button {{
      border: 1px solid rgba(0,0,0,0.14);
      border-radius: 999px;
      background: white;
      color: var(--ink);
      padding: 8px 12px;
      font: inherit;
      cursor: pointer;
      text-transform: uppercase;
      letter-spacing: 0.06em;
    }}
    .toolbar button:hover {{
      background: rgb(247, 247, 243);
    }}
    .toolbar .hint {{
      opacity: 0.72;
      text-align: right;
    }}
    canvas {{
      display: block;
      width: 100%;
      height: auto;
      background: var(--paper);
      cursor: grab;
      touch-action: none;
      user-select: none;
    }}
    canvas.is-dragging {{
      cursor: grabbing;
    }}
    .meta {{
      display: flex;
      justify-content: space-between;
      flex-wrap: wrap;
      gap: 12px;
      padding: 10px 14px;
      border-top: 1px solid rgba(0,0,0,0.08);
      background: rgba(250,250,248,0.9);
      font-size: 12px;
      letter-spacing: 0.02em;
      text-transform: uppercase;
    }}
    .meta .right {{
      display: flex;
      gap: 14px;
    }}
  </style>
</head>
<body>
  <main>
    <div class="frame">
      <div class="toolbar">
        <button id="reset-view" type="button">Reset View</button>
        <span class="hint">Drag a point to edit, drag empty space to pan, wheel to zoom</span>
      </div>
      <canvas id="view" width="{width}" height="{height}"></canvas>
      <div class="meta">
        <span>Generated by gsp-rs</span>
        <span>{shape_count} shapes</span>
        <div class="right">
          <span id="coord-readout">x -, y -</span>
          <span id="zoom-readout">zoom 100%</span>
        </div>
      </div>
    </div>
  </main>
  <script id="scene-data" type="application/json">{scene_json}</script>
  <script>
    const sourceScene = JSON.parse(document.getElementById('scene-data').textContent);
    const canvas = document.getElementById('view');
    const ctx = canvas.getContext('2d');
    const resetButton = document.getElementById('reset-view');
    const coordReadout = document.getElementById('coord-readout');
    const zoomReadout = document.getElementById('zoom-readout');
    const margin = 32;
    const trigMode = !!sourceScene.piMode;
    const savedViewportMode = !!sourceScene.savedViewport;
    const baseBounds = sourceScene.bounds;
    const baseCenterX = (baseBounds.minX + baseBounds.maxX) / 2;
    const baseCenterY = (baseBounds.minY + baseBounds.maxY) / 2;
    const baseSpanX = Math.max(1e-6, baseBounds.maxX - baseBounds.minX);
    const baseSpanY = Math.max(1e-6, baseBounds.maxY - baseBounds.minY);
    const pointHitRadius = 10;
    const pointMatchTolerance = 1e-3;
    const view = {{
      centerX: baseCenterX,
      centerY: baseCenterY,
      zoom: 1,
    }};
    let dragState = null;
    let hoverPointIndex = null;

    function samePoint(left, right) {{
      return Math.abs(left.x - right.x) < pointMatchTolerance
        && Math.abs(left.y - right.y) < pointMatchTolerance;
    }}

    function resolveSourcePoint(index) {{
      const point = sourceScene.points[index];
      if (!point) {{
        return {{ x: 0, y: 0 }};
      }}
      if (point.constraint && point.constraint.kind === 'segment') {{
        const start = resolveSourcePoint(point.constraint.startIndex);
        const end = resolveSourcePoint(point.constraint.endIndex);
        return {{
          x: start.x + (end.x - start.x) * point.constraint.t,
          y: start.y + (end.y - start.y) * point.constraint.t,
        }};
      }}
      return {{ x: point.x, y: point.y }};
    }}

    function attachPointRef(point) {{
      const pointIndex = sourceScene.points.findIndex((candidate, index) => samePoint(resolveSourcePoint(index), point));
      if (pointIndex >= 0) {{
        return {{ pointIndex }};
      }}
      return {{ x: point.x, y: point.y }};
    }}

    function hydrateScene(scene) {{
      return {{
        graphMode: scene.graphMode,
        points: scene.points.map((point) => ({{
          x: point.x,
          y: point.y,
          constraint: point.constraint ? {{ ...point.constraint }} : null,
        }})),
        origin: scene.origin ? attachPointRef(scene.origin) : null,
        lines: scene.lines.map((line) => ({{
          color: line.color,
          dashed: line.dashed,
          points: line.points.map(attachPointRef),
        }})),
        polygons: scene.polygons.map((polygon) => ({{
          color: polygon.color,
          outlineColor: polygon.outlineColor,
          points: polygon.points.map(attachPointRef),
        }})),
        circles: scene.circles.map((circle) => ({{
          color: circle.color,
          center: attachPointRef(circle.center),
          radiusPoint: attachPointRef(circle.radiusPoint),
        }})),
        labels: scene.labels.map((label) => ({{
          text: label.text,
          color: label.color,
          anchor: attachPointRef(label.anchor),
        }})),
      }};
    }}

    const scene = hydrateScene(sourceScene);

    function getViewBounds() {{
      const spanX = baseSpanX / view.zoom;
      const spanY = baseSpanY / view.zoom;
      return {{
        minX: view.centerX - spanX / 2,
        maxX: view.centerX + spanX / 2,
        minY: view.centerY - spanY / 2,
        maxY: view.centerY + spanY / 2,
        spanX,
        spanY,
      }};
    }}

    function resolvePoint(handle) {{
      if (typeof handle.pointIndex === 'number') {{
        return resolveScenePoint(handle.pointIndex);
      }}
      return handle;
    }}

    function resolveScenePoint(index) {{
      const point = scene.points[index];
      if (!point) {{
        return {{ x: 0, y: 0 }};
      }}
      if (point.constraint && point.constraint.kind === 'segment') {{
        const start = resolveScenePoint(point.constraint.startIndex);
        const end = resolveScenePoint(point.constraint.endIndex);
        return {{
          x: start.x + (end.x - start.x) * point.constraint.t,
          y: start.y + (end.y - start.y) * point.constraint.t,
        }};
      }}
      return point;
    }}

    function toScreen(point) {{
      const usableWidth = Math.max(1, sourceScene.width - margin * 2);
      const usableHeight = Math.max(1, sourceScene.height - margin * 2);
      const bounds = getViewBounds();
      const scale = Math.min(usableWidth / bounds.spanX, usableHeight / bounds.spanY);
      return {{
        x: margin + (point.x - bounds.minX) * scale,
        y: sourceScene.yUp
          ? sourceScene.height - margin - (point.y - bounds.minY) * scale
          : margin + (point.y - bounds.minY) * scale,
        scale,
      }};
    }}

    function toWorld(screenX, screenY) {{
      const usableWidth = Math.max(1, sourceScene.width - margin * 2);
      const usableHeight = Math.max(1, sourceScene.height - margin * 2);
      const bounds = getViewBounds();
      const scale = Math.min(usableWidth / bounds.spanX, usableHeight / bounds.spanY);
      return {{
        x: bounds.minX + (screenX - margin) / scale,
        y: sourceScene.yUp
          ? bounds.minY + (sourceScene.height - margin - screenY) / scale
          : bounds.minY + (screenY - margin) / scale,
        scale,
      }};
    }}

    function getCanvasCoords(event) {{
      const rect = canvas.getBoundingClientRect();
      return {{
        x: (event.clientX - rect.left) * (sourceScene.width / rect.width),
        y: (event.clientY - rect.top) * (sourceScene.height / rect.height),
      }};
    }}

    function rgba(color) {{
      return `rgba(${{color[0]}}, ${{color[1]}}, ${{color[2]}}, ${{(color[3] / 255).toFixed(3)}})`;
    }}

    function formatNumber(value) {{
      return Number.isFinite(value) ? value.toFixed(2) : '-';
    }}

    function chooseGridStep(span, targetLines) {{
      const rough = Math.max(1e-6, span / Math.max(1, targetLines));
      const magnitude = 10 ** Math.floor(Math.log10(rough));
      const normalized = rough / magnitude;
      if (normalized <= 1) return magnitude;
      if (normalized <= 2) return magnitude * 2;
      if (normalized <= 5) return magnitude * 5;
      return magnitude * 10;
    }}

    function formatAxisNumber(value) {{
      if (Math.abs(value - Math.round(value)) < 1e-6) {{
        return String(Math.round(value));
      }}
      return value.toFixed(1);
    }}

    function formatPiLabel(stepIndex) {{
      if (stepIndex === 0) return '';
      const sign = stepIndex < 0 ? '-' : '';
      const absIndex = Math.abs(stepIndex);
      if (absIndex % 2 === 0) {{
        const multiple = absIndex / 2;
        return multiple === 1 ? `${{sign}}π` : `${{sign}}${{multiple}}π`;
      }}
      return absIndex === 1 ? `${{sign}}π/2` : `${{sign}}${{absIndex}}π/2`;
    }}

    function updateReadout(screenX = null, screenY = null) {{
      zoomReadout.textContent = `zoom ${{Math.round(view.zoom * 100)}}%`;
      if (screenX === null || screenY === null) {{
        coordReadout.textContent = 'x -, y -';
        return;
      }}
      const world = toWorld(screenX, screenY);
      coordReadout.textContent = `x ${{formatNumber(world.x)}}, y ${{formatNumber(world.y)}}`;
    }}

    function resetView() {{
      view.centerX = baseCenterX;
      view.centerY = baseCenterY;
      view.zoom = 1;
      updateReadout();
      draw();
    }}

    function drawGrid() {{
      if (!scene.graphMode) return;
      const bounds = getViewBounds();
      const spanY = bounds.maxY - bounds.minY;
      const yMinorStep = savedViewportMode ? 1 : chooseGridStep(spanY, 14);
      const yMajorStep = savedViewportMode ? 2 : chooseGridStep(spanY, 7);
      const minYIndex = Math.floor(bounds.minY / yMinorStep);
      const maxYIndex = Math.ceil(bounds.maxY / yMinorStep);

      ctx.save();
      ctx.lineWidth = 1;
      ctx.font = '12px "Noto Sans", "Segoe UI", sans-serif';
      ctx.fillStyle = 'rgb(20,20,20)';
      const xAxisY = bounds.minY <= 0 && 0 <= bounds.maxY
        ? toScreen({{ x: bounds.minX, y: 0 }}).y
        : sourceScene.height - 18;
      const yAxisX = bounds.minX <= 0 && 0 <= bounds.maxX
        ? toScreen({{ x: 0, y: bounds.minY }}).x
        : sourceScene.width / 2;
      if (trigMode) {{
        const xMinorStep = Math.PI / 2;
        const startIndex = Math.ceil(bounds.minX / xMinorStep);
        const endIndex = Math.floor(bounds.maxX / xMinorStep);
        for (let stepIndex = startIndex; stepIndex <= endIndex; stepIndex += 1) {{
          const x = stepIndex * xMinorStep;
          const screen = toScreen({{ x, y: bounds.minY }});
          const major = stepIndex % 2 === 0;
          ctx.strokeStyle = Math.abs(x) < 1e-9
            ? 'rgb(40,40,40)'
            : major
              ? 'rgb(190,190,190)'
              : 'rgb(220,220,220)';
          ctx.beginPath();
          ctx.moveTo(screen.x, 0);
          ctx.lineTo(screen.x, sourceScene.height);
          ctx.stroke();
          if (bounds.minY <= 0 && 0 <= bounds.maxY) {{
            ctx.strokeStyle = 'rgb(40,40,40)';
            ctx.beginPath();
            ctx.moveTo(screen.x, xAxisY - (major ? 6 : 4));
            ctx.lineTo(screen.x, xAxisY + (major ? 6 : 4));
            ctx.stroke();
          }}
          if (major && stepIndex !== 0) {{
            const label = formatPiLabel(stepIndex);
            const width = ctx.measureText(label).width;
            ctx.fillText(
              label,
              screen.x - width / 2,
              Math.min(sourceScene.height - 4, xAxisY + 16),
            );
          }}
        }}
      }} else {{
        const spanX = bounds.maxX - bounds.minX;
        const xLabelStep = spanX > 20 ? 5 : 2;
        const minX = Math.floor(bounds.minX);
        const maxX = Math.ceil(bounds.maxX);
        for (let x = minX; x <= maxX; x += 1) {{
          const screen = toScreen({{ x, y: bounds.minY }});
          ctx.strokeStyle = x === 0 ? 'rgb(40,40,40)' : 'rgb(200,200,200)';
          ctx.beginPath();
          ctx.moveTo(screen.x, 0);
          ctx.lineTo(screen.x, sourceScene.height);
          ctx.stroke();
          if (bounds.minY <= 0 && 0 <= bounds.maxY) {{
            ctx.strokeStyle = 'rgb(40,40,40)';
            ctx.beginPath();
            ctx.moveTo(screen.x, xAxisY - (x === 0 ? 6 : 4));
            ctx.lineTo(screen.x, xAxisY + (x === 0 ? 6 : 4));
            ctx.stroke();
          }}
          if (x !== 0 && x % xLabelStep === 0) {{
            const label = String(x);
            const width = ctx.measureText(label).width;
            ctx.fillText(
              label,
              screen.x - width / 2,
              Math.min(sourceScene.height - 4, xAxisY + 16),
            );
          }}
        }}
      }}
      for (let yIndex = minYIndex; yIndex <= maxYIndex; yIndex += 1) {{
        const y = yIndex * yMinorStep;
        const major = Math.abs((y / yMajorStep) - Math.round(y / yMajorStep)) < 1e-6;
        const screen = toScreen({{ x: bounds.minX, y }});
        ctx.strokeStyle = Math.abs(y) < 1e-6
          ? 'rgb(40,40,40)'
          : major
            ? 'rgb(200,200,200)'
            : 'rgb(225,225,225)';
        ctx.beginPath();
        ctx.moveTo(0, screen.y);
        ctx.lineTo(sourceScene.width, screen.y);
        ctx.stroke();
        if (bounds.minX <= 0 && 0 <= bounds.maxX) {{
          ctx.strokeStyle = 'rgb(40,40,40)';
          ctx.beginPath();
          ctx.moveTo(yAxisX - (Math.abs(y) < 1e-6 ? 6 : major ? 4 : 2), screen.y);
          ctx.lineTo(yAxisX + (Math.abs(y) < 1e-6 ? 6 : major ? 4 : 2), screen.y);
          ctx.stroke();
        }}
        if (major && Math.abs(y) >= 1e-6) {{
          const label = formatAxisNumber(y);
          const width = ctx.measureText(label).width;
          ctx.fillText(label, yAxisX - width - 8, screen.y - 6);
        }}
      }}
      if (scene.origin) {{
        const origin = toScreen(resolvePoint(scene.origin));
        ctx.fillStyle = 'rgba(255, 60, 40, 1)';
        ctx.beginPath();
        ctx.arc(origin.x, origin.y, 3, 0, Math.PI * 2);
        ctx.fill();
      }}
      ctx.restore();
    }}

    function findHitPoint(screenX, screenY) {{
      let bestIndex = null;
      let bestDistanceSquared = pointHitRadius * pointHitRadius;
      scene.points.forEach((_, index) => {{
        const screen = toScreen(resolveScenePoint(index));
        const dx = screen.x - screenX;
        const dy = screen.y - screenY;
        const distanceSquared = dx * dx + dy * dy;
        if (distanceSquared <= bestDistanceSquared) {{
          bestDistanceSquared = distanceSquared;
          bestIndex = index;
        }}
      }});
      return bestIndex;
    }}

    function isOriginPointIndex(index) {{
      return typeof scene.origin?.pointIndex === 'number' && scene.origin.pointIndex === index;
    }}

    function draw() {{
      ctx.clearRect(0, 0, sourceScene.width, sourceScene.height);
      ctx.fillStyle = 'rgb(250,250,248)';
      ctx.fillRect(0, 0, sourceScene.width, sourceScene.height);
      drawGrid();

      for (const polygon of scene.polygons) {{
        if (polygon.points.length < 3) continue;
        ctx.beginPath();
        polygon.points.forEach((handle, index) => {{
          const screen = toScreen(resolvePoint(handle));
          if (index === 0) {{
            ctx.moveTo(screen.x, screen.y);
          }} else {{
            ctx.lineTo(screen.x, screen.y);
          }}
        }});
        ctx.closePath();
        ctx.fillStyle = rgba(polygon.color);
        ctx.strokeStyle = rgba(polygon.outlineColor);
        ctx.lineWidth = 1.5;
        ctx.fill();
        ctx.stroke();
      }}

      for (const line of scene.lines) {{
        if (line.points.length < 2) continue;
        ctx.beginPath();
        line.points.forEach((handle, index) => {{
          const screen = toScreen(resolvePoint(handle));
          if (index === 0) {{
            ctx.moveTo(screen.x, screen.y);
          }} else {{
            ctx.lineTo(screen.x, screen.y);
          }}
        }});
        ctx.strokeStyle = rgba(line.color);
        ctx.lineWidth = 2;
        ctx.setLineDash(line.dashed ? [8, 8] : []);
        ctx.stroke();
      }}
      ctx.setLineDash([]);

      for (const circle of scene.circles) {{
        const centerWorld = resolvePoint(circle.center);
        const radiusPointWorld = resolvePoint(circle.radiusPoint);
        const center = toScreen(centerWorld);
        const radius = Math.hypot(
          radiusPointWorld.x - centerWorld.x,
          radiusPointWorld.y - centerWorld.y,
        ) * center.scale;
        ctx.beginPath();
        ctx.arc(center.x, center.y, radius, 0, Math.PI * 2);
        ctx.strokeStyle = rgba(circle.color);
        ctx.lineWidth = 2;
        ctx.stroke();
      }}

      scene.points.forEach((point, index) => {{
        const screen = toScreen(resolveScenePoint(index));
        ctx.beginPath();
        ctx.arc(screen.x, screen.y, index === hoverPointIndex ? 6 : 4, 0, Math.PI * 2);
        ctx.fillStyle = index === hoverPointIndex ? 'rgba(255, 120, 20, 1)' : 'rgba(255, 60, 40, 1)';
        ctx.fill();
      }});

      ctx.font = '18px "Noto Sans", "Segoe UI", sans-serif';
      ctx.textBaseline = 'top';
      for (const label of scene.labels) {{
        const screen = toScreen(resolvePoint(label.anchor));
        ctx.fillStyle = rgba(label.color);
        const lines = label.text.split('\n');
        lines.forEach((line, index) => {{
          ctx.fillText(line, screen.x + 6, screen.y - 10 + index * 22);
        }});
      }}
    }}

    canvas.addEventListener('pointerdown', (event) => {{
      const position = getCanvasCoords(event);
      const pointIndex = findHitPoint(position.x, position.y);
      dragState = {{
        pointerId: event.pointerId,
        mode: pointIndex === null
          ? 'pan'
          : (scene.graphMode && isOriginPointIndex(pointIndex) ? 'origin-pan' : 'point'),
        pointIndex,
        lastX: position.x,
        lastY: position.y,
      }};
      hoverPointIndex = pointIndex;
      canvas.classList.add('is-dragging');
      canvas.setPointerCapture(event.pointerId);
      draw();
    }});

    canvas.addEventListener('pointermove', (event) => {{
      const position = getCanvasCoords(event);
      updateReadout(position.x, position.y);
      hoverPointIndex = findHitPoint(position.x, position.y);
      if (!dragState || dragState.pointerId !== event.pointerId) {{
        draw();
        return;
      }}
      if (dragState.mode === 'point') {{
        const world = toWorld(position.x, position.y);
        const point = scene.points[dragState.pointIndex];
        if (point.constraint && point.constraint.kind === 'segment') {{
          const start = resolveScenePoint(point.constraint.startIndex);
          const end = resolveScenePoint(point.constraint.endIndex);
          const dx = end.x - start.x;
          const dy = end.y - start.y;
          const lengthSquared = dx * dx + dy * dy;
          if (lengthSquared > 1e-9) {{
            const t = ((world.x - start.x) * dx + (world.y - start.y) * dy) / lengthSquared;
            point.constraint.t = Math.max(0, Math.min(1, t));
          }}
        }} else {{
          point.x = world.x;
          point.y = world.y;
        }}
        hoverPointIndex = dragState.pointIndex;
      }} else {{
        const worldNow = toWorld(position.x, position.y);
        const worldLast = toWorld(dragState.lastX, dragState.lastY);
        view.centerX -= worldNow.x - worldLast.x;
        view.centerY -= worldNow.y - worldLast.y;
      }}
      dragState.lastX = position.x;
      dragState.lastY = position.y;
      draw();
    }});

    function endDrag(pointerId) {{
      if (dragState && dragState.pointerId === pointerId) {{
        dragState = null;
        canvas.classList.remove('is-dragging');
      }}
    }}

    canvas.addEventListener('pointerup', (event) => endDrag(event.pointerId));
    canvas.addEventListener('pointercancel', (event) => endDrag(event.pointerId));
    canvas.addEventListener('pointerleave', () => {{
      hoverPointIndex = null;
      if (!dragState) {{
        updateReadout();
        draw();
      }}
    }});

    canvas.addEventListener('wheel', (event) => {{
      event.preventDefault();
      const position = getCanvasCoords(event);
      const before = toWorld(position.x, position.y);
      const factor = event.deltaY < 0 ? 1.1 : 1 / 1.1;
      view.zoom = Math.max(0.25, Math.min(64, view.zoom * factor));
      const after = toWorld(position.x, position.y);
      view.centerX += before.x - after.x;
      view.centerY += before.y - after.y;
      updateReadout(position.x, position.y);
      draw();
    }}, {{ passive: false }});

    canvas.addEventListener('dblclick', () => {{
      resetView();
    }});

    resetButton.addEventListener('click', () => {{
      resetView();
    }});

    window.addEventListener('keydown', (event) => {{
      if (event.key === '0') {{
        resetView();
      }}
    }});

    resetView();
  </script>
</body>
</html>
"#,
        frame_width = width + 40,
        width = width,
        height = height,
        shape_count =
            scene.lines.len() + scene.polygons.len() + scene.circles.len() + scene.labels.len(),
        scene_json = scene_json,
    );
    html
}

fn scene_to_json(scene: &Scene, width: u32, height: u32) -> String {
    let mut out = String::new();
    out.push('{');
    let _ = write!(
        out,
        "\"width\":{width},\"height\":{height},\"graphMode\":{},\"piMode\":{},\"savedViewport\":{},\"yUp\":{},\"bounds\":{{\"minX\":{},\"maxX\":{},\"minY\":{},\"maxY\":{}}},",
        if scene.graph_mode { "true" } else { "false" },
        if scene.pi_mode { "true" } else { "false" },
        if scene.saved_viewport { "true" } else { "false" },
        if scene.y_up { "true" } else { "false" },
        format_f64(scene.bounds.min_x),
        format_f64(scene.bounds.max_x),
        format_f64(scene.bounds.min_y),
        format_f64(scene.bounds.max_y),
    );
    out.push_str("\"origin\":");
    match &scene.origin {
        Some(point) => push_point_json(&mut out, point),
        None => out.push_str("null"),
    }
    out.push(',');
    out.push_str("\"lines\":[");
    for (index, line) in scene.lines.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        out.push_str("\"points\":[");
        for (point_index, point) in line.points.iter().enumerate() {
            if point_index > 0 {
                out.push(',');
            }
            push_point_json(&mut out, point);
        }
        let _ = write!(
            out,
            "],\"color\":[{},{},{},{}],\"dashed\":{}",
            line.color[0],
            line.color[1],
            line.color[2],
            line.color[3],
            if line.dashed { "true" } else { "false" },
        );
        out.push('}');
    }
    out.push_str("],\"polygons\":[");
    for (index, polygon) in scene.polygons.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        out.push_str("\"points\":[");
        for (point_index, point) in polygon.points.iter().enumerate() {
            if point_index > 0 {
                out.push(',');
            }
            push_point_json(&mut out, point);
        }
        let outline = darken(polygon.color, 80);
        let _ = write!(
            out,
            "],\"color\":[{},{},{},{}],\"outlineColor\":[{},{},{},{}]",
            polygon.color[0],
            polygon.color[1],
            polygon.color[2],
            polygon.color[3],
            outline[0],
            outline[1],
            outline[2],
            outline[3],
        );
        out.push('}');
    }
    out.push_str("],\"circles\":[");
    for (index, circle) in scene.circles.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        out.push_str("\"center\":");
        push_point_json(&mut out, &circle.center);
        out.push_str(",\"radiusPoint\":");
        push_point_json(&mut out, &circle.radius_point);
        let _ = write!(
            out,
            ",\"color\":[{},{},{},{}]",
            circle.color[0], circle.color[1], circle.color[2], circle.color[3],
        );
        out.push('}');
    }
    out.push_str("],\"labels\":[");
    for (index, label) in scene.labels.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        out.push_str("\"anchor\":");
        push_point_json(&mut out, &label.anchor);
        let _ = write!(
            out,
            ",\"text\":\"{}\",\"color\":[{},{},{},{}]",
            escape_json_string(&label.text),
            label.color[0],
            label.color[1],
            label.color[2],
            label.color[3],
        );
        out.push('}');
    }
    out.push_str("],\"points\":[");
    for (index, point) in scene.points.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        let _ = write!(
            out,
            "\"x\":{},\"y\":{}",
            format_f64(point.position.x),
            format_f64(point.position.y),
        );
        match &point.constraint {
            ScenePointConstraint::Free => out.push_str(",\"constraint\":null"),
            ScenePointConstraint::OnSegment {
                start_index,
                end_index,
                t,
            } => {
                let _ = write!(
                    out,
                    ",\"constraint\":{{\"kind\":\"segment\",\"startIndex\":{},\"endIndex\":{},\"t\":{}}}",
                    start_index,
                    end_index,
                    format_f64(*t),
                );
            }
        }
        out.push('}');
    }
    out.push_str("]}");
    out
}

fn push_point_json(out: &mut String, point: &PointRecord) {
    let _ = write!(
        out,
        "{{\"x\":{},\"y\":{}}}",
        format_f64(point.x),
        format_f64(point.y),
    );
}

fn format_f64(value: f64) -> String {
    if value.is_finite() {
        let mut text = format!("{value:.6}");
        while text.contains('.') && text.ends_with('0') {
            text.pop();
        }
        if text.ends_with('.') {
            text.push('0');
        }
        text
    } else {
        "0".to_string()
    }
}

fn escape_json_string(text: &str) -> String {
    let mut escaped = String::new();
    for ch in text.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            ch if ch.is_control() => {
                let _ = write!(escaped, "\\u{:04x}", ch as u32);
            }
            _ => escaped.push(ch),
        }
    }
    escaped
}
