use crate::format::{GspFile, PointRecord};
use crate::render::extract::build_scene;
use crate::render::functions::{BinaryOp, FunctionExpr, FunctionTerm, UnaryFunction};
use crate::render::geometry::darken;
use crate::render::scene::{Scene, ScenePointConstraint};
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const VIEWER_CSS: &str = include_str!("html/viewer.css");
const VIEWER_JS: &str = include_str!("html/viewer.js");

pub fn render_points_to_html(
    file: &GspFile,
    output_path: &Path,
    width: u32,
    height: u32,
) -> Result<(), String> {
    if !matches!(
        output_path.extension().and_then(|ext| ext.to_str()),
        Some("html") | Some("HTML") | Some("htm") | Some("HTM")
    ) {
        return Err(format!(
            "html output path must end with .html or .htm: {}",
            output_path.display()
        ));
    }

    let scene = build_scene(file);
    let html = build_standalone_html(&scene, width, height);

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "failed to create html output directory {}: {error}",
                parent.display()
            )
        })?;
    }

    fs::write(output_path, html)
        .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    Ok(())
}

fn build_standalone_html(scene: &Scene, width: u32, height: u32) -> String {
    let mut html = String::new();
    let scene_json = scene_to_json(scene, width, height);
    let frame_width = width + 40;
    let shape_count =
        scene.lines.len() + scene.polygons.len() + scene.circles.len() + scene.labels.len();
    let _ = write!(
        html,
        r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>gsp-rs export</title>
  <style>
    :root {{
      --frame-width: {frame_width}px;
    }}
{embedded_css}
  </style>
</head>
<body>
  <main>
    <div class="frame">
      <div class="toolbar">
        <div class="controls">
          <button id="reset-view" type="button">Reset View</button>
          <div id="parameter-controls"></div>
        </div>
        <span class="hint">Drag a point to edit, drag empty space to pan, wheel to zoom</span>
      </div>
      <canvas id="view" width="{width}" height="{height}"></canvas>
      <div class="meta">
        <span>Generated by gsp-rs</span>
        <span>{shape_count} shapes</span>
        <div class="right">
          <span id="coord-readout">x -, y -</span>
          <span id="zoom-readout">zoom 100%</span>
        </div>
      </div>
    </div>
  </main>
  <script id="scene-data" type="application/json">{scene_json}</script>
  <script>
{embedded_js}
  </script>
</body>
</html>
"#,
        width = width,
        height = height,
        frame_width = frame_width,
        shape_count = shape_count,
        scene_json = scene_json,
        embedded_css = indent_asset(VIEWER_CSS, 4),
        embedded_js = indent_asset(VIEWER_JS, 4),
    );
    html
}

fn indent_asset(asset: &str, spaces: usize) -> String {
    let indent = " ".repeat(spaces);
    asset
        .lines()
        .map(|line| format!("{indent}{line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn scene_to_json(scene: &Scene, width: u32, height: u32) -> String {
    let mut out = String::new();
    out.push('{');
    let _ = write!(
        out,
        "\"width\":{width},\"height\":{height},\"graphMode\":{},\"piMode\":{},\"savedViewport\":{},\"yUp\":{},\"bounds\":{{\"minX\":{},\"maxX\":{},\"minY\":{},\"maxY\":{}}},",
        if scene.graph_mode { "true" } else { "false" },
        if scene.pi_mode { "true" } else { "false" },
        if scene.saved_viewport {
            "true"
        } else {
            "false"
        },
        if scene.y_up { "true" } else { "false" },
        format_f64(scene.bounds.min_x),
        format_f64(scene.bounds.max_x),
        format_f64(scene.bounds.min_y),
        format_f64(scene.bounds.max_y),
    );
    out.push_str("\"origin\":");
    match &scene.origin {
        Some(point) => push_point_json(&mut out, point),
        None => out.push_str("null"),
    }
    out.push(',');
    out.push_str("\"lines\":[");
    for (index, line) in scene.lines.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        out.push_str("\"points\":[");
        for (point_index, point) in line.points.iter().enumerate() {
            if point_index > 0 {
                out.push(',');
            }
            push_point_json(&mut out, point);
        }
        let _ = write!(
            out,
            "],\"color\":[{},{},{},{}],\"dashed\":{}",
            line.color[0],
            line.color[1],
            line.color[2],
            line.color[3],
            if line.dashed { "true" } else { "false" },
        );
        out.push('}');
    }
    out.push_str("],\"polygons\":[");
    for (index, polygon) in scene.polygons.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        out.push_str("\"points\":[");
        for (point_index, point) in polygon.points.iter().enumerate() {
            if point_index > 0 {
                out.push(',');
            }
            push_point_json(&mut out, point);
        }
        let outline = darken(polygon.color, 80);
        let _ = write!(
            out,
            "],\"color\":[{},{},{},{}],\"outlineColor\":[{},{},{},{}]",
            polygon.color[0],
            polygon.color[1],
            polygon.color[2],
            polygon.color[3],
            outline[0],
            outline[1],
            outline[2],
            outline[3],
        );
        out.push('}');
    }
    out.push_str("],\"circles\":[");
    for (index, circle) in scene.circles.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        out.push_str("\"center\":");
        push_point_json(&mut out, &circle.center);
        out.push_str(",\"radiusPoint\":");
        push_point_json(&mut out, &circle.radius_point);
        let _ = write!(
            out,
            ",\"color\":[{},{},{},{}]",
            circle.color[0], circle.color[1], circle.color[2], circle.color[3],
        );
        out.push('}');
    }
    out.push_str("],\"labels\":[");
    for (index, label) in scene.labels.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        out.push_str("\"anchor\":");
        push_point_json(&mut out, &label.anchor);
        let _ = write!(
            out,
            ",\"text\":\"{}\",\"color\":[{},{},{},{}]",
            escape_json_string(&label.text),
            label.color[0],
            label.color[1],
            label.color[2],
            label.color[3],
        );
        out.push('}');
    }
    out.push_str("],\"points\":[");
    for (index, point) in scene.points.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        let _ = write!(
            out,
            "\"x\":{},\"y\":{}",
            format_f64(point.position.x),
            format_f64(point.position.y),
        );
        match &point.constraint {
            ScenePointConstraint::Free => out.push_str(",\"constraint\":null"),
            ScenePointConstraint::OnSegment {
                start_index,
                end_index,
                t,
            } => {
                let _ = write!(
                    out,
                    ",\"constraint\":{{\"kind\":\"segment\",\"startIndex\":{},\"endIndex\":{},\"t\":{}}}",
                    start_index,
                    end_index,
                    format_f64(*t),
                );
            }
            ScenePointConstraint::OnPolyline {
                function_key,
                points,
                segment_index,
                t,
            } => {
                let point_json = points
                    .iter()
                    .map(|point| {
                        format!(
                            "{{\"x\":{},\"y\":{}}}",
                            format_f64(point.x),
                            format_f64(point.y)
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(",");
                let _ = write!(
                    out,
                    ",\"constraint\":{{\"kind\":\"polyline\",\"functionKey\":{},\"points\":[{}],\"segmentIndex\":{},\"t\":{}}}",
                    function_key,
                    point_json,
                    segment_index,
                    format_f64(*t),
                );
            }
            ScenePointConstraint::OnPolygonBoundary {
                vertex_indices,
                edge_index,
                t,
            } => {
                let _ = write!(
                    out,
                    ",\"constraint\":{{\"kind\":\"polygon-boundary\",\"vertexIndices\":[{}],\"edgeIndex\":{},\"t\":{}}}",
                    vertex_indices
                        .iter()
                        .map(|index| index.to_string())
                        .collect::<Vec<_>>()
                        .join(","),
                    edge_index,
                    format_f64(*t),
                );
            }
            ScenePointConstraint::OnCircle {
                center_index,
                radius_index,
                unit_x,
                unit_y,
            } => {
                let _ = write!(
                    out,
                    ",\"constraint\":{{\"kind\":\"circle\",\"centerIndex\":{},\"radiusIndex\":{},\"unitX\":{},\"unitY\":{}}}",
                    center_index,
                    radius_index,
                    format_f64(*unit_x),
                    format_f64(*unit_y),
                );
            }
        }
        out.push('}');
    }
    out.push_str("],\"parameters\":[");
    for (index, parameter) in scene.parameters.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        let _ = write!(
            out,
            "{{\"name\":\"{}\",\"value\":{},\"labelIndex\":{}}}",
            escape_json_string(&parameter.name),
            format_f64(parameter.value),
            parameter.label_index,
        );
    }
    out.push_str("],\"functions\":[");
    for (index, function_def) in scene.functions.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        out.push('{');
        let _ = write!(
            out,
            "\"key\":{},\"name\":\"{}\",\"derivative\":{},\"domain\":{{\"xMin\":{},\"xMax\":{},\"sampleCount\":{}}},\"lineIndex\":{},\"labelIndex\":{},\"constrainedPointIndices\":[{}],\"expr\":",
            function_def.key,
            escape_json_string(&function_def.name),
            if function_def.derivative {
                "true"
            } else {
                "false"
            },
            format_f64(function_def.domain.x_min),
            format_f64(function_def.domain.x_max),
            function_def.domain.sample_count,
            function_def
                .line_index
                .map(|index| index.to_string())
                .unwrap_or_else(|| "null".to_string()),
            function_def.label_index,
            function_def
                .constrained_point_indices
                .iter()
                .map(|index| index.to_string())
                .collect::<Vec<_>>()
                .join(","),
        );
        push_function_expr_json(&mut out, &function_def.expr);
        out.push('}');
    }
    out.push_str("]}");
    out
}

fn push_point_json(out: &mut String, point: &PointRecord) {
    let _ = write!(
        out,
        "{{\"x\":{},\"y\":{}}}",
        format_f64(point.x),
        format_f64(point.y),
    );
}

fn push_function_expr_json(out: &mut String, expr: &FunctionExpr) {
    match expr {
        FunctionExpr::Constant(value) => {
            let _ = write!(
                out,
                "{{\"kind\":\"constant\",\"value\":{}}}",
                format_f64(*value)
            );
        }
        FunctionExpr::Identity => out.push_str("{\"kind\":\"identity\"}"),
        FunctionExpr::SinIdentity => out.push_str(
            "{\"kind\":\"parsed\",\"head\":{\"kind\":\"unary_x\",\"op\":\"sin\"},\"tail\":[]}",
        ),
        FunctionExpr::CosIdentityPlus(offset) => {
            out.push_str(
                "{\"kind\":\"parsed\",\"head\":{\"kind\":\"unary_x\",\"op\":\"cos\"},\"tail\":[",
            );
            out.push_str("{\"op\":\"add\",\"term\":");
            push_function_term_json(out, &FunctionTerm::Constant(*offset));
            out.push_str("}]}");
        }
        FunctionExpr::TanIdentityMinus(offset) => {
            out.push_str(
                "{\"kind\":\"parsed\",\"head\":{\"kind\":\"unary_x\",\"op\":\"tan\"},\"tail\":[",
            );
            out.push_str("{\"op\":\"sub\",\"term\":");
            push_function_term_json(out, &FunctionTerm::Constant(*offset));
            out.push_str("}]}");
        }
        FunctionExpr::Parsed(parsed) => {
            out.push_str("{\"kind\":\"parsed\",\"head\":");
            push_function_term_json(out, &parsed.head);
            out.push_str(",\"tail\":[");
            for (index, (op, term)) in parsed.tail.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                let op_name = match op {
                    BinaryOp::Add => "add",
                    BinaryOp::Sub => "sub",
                    BinaryOp::Mul => "mul",
                };
                let _ = write!(out, "{{\"op\":\"{}\",\"term\":", op_name);
                push_function_term_json(out, term);
                out.push('}');
            }
            out.push_str("]}");
        }
    }
}

fn push_function_term_json(out: &mut String, term: &FunctionTerm) {
    match term {
        FunctionTerm::Variable => out.push_str("{\"kind\":\"variable\"}"),
        FunctionTerm::Constant(value) => {
            let _ = write!(
                out,
                "{{\"kind\":\"constant\",\"value\":{}}}",
                format_f64(*value)
            );
        }
        FunctionTerm::Parameter(name, value) => {
            let _ = write!(
                out,
                "{{\"kind\":\"parameter\",\"name\":\"{}\",\"value\":{}}}",
                escape_json_string(name),
                format_f64(*value),
            );
        }
        FunctionTerm::UnaryX(op) => {
            let op_name = match op {
                UnaryFunction::Sin => "sin",
                UnaryFunction::Cos => "cos",
                UnaryFunction::Tan => "tan",
                UnaryFunction::Abs => "abs",
                UnaryFunction::Sqrt => "sqrt",
                UnaryFunction::Ln => "ln",
                UnaryFunction::Log10 => "log10",
                UnaryFunction::Sign => "sign",
                UnaryFunction::Round => "round",
                UnaryFunction::Trunc => "trunc",
            };
            let _ = write!(out, "{{\"kind\":\"unary_x\",\"op\":\"{}\"}}", op_name);
        }
        FunctionTerm::Product(left, right) => {
            out.push_str("{\"kind\":\"product\",\"left\":");
            push_function_term_json(out, left);
            out.push_str(",\"right\":");
            push_function_term_json(out, right);
            out.push('}');
        }
    }
}

fn format_f64(value: f64) -> String {
    if value.is_finite() {
        let mut text = format!("{value:.6}");
        while text.contains('.') && text.ends_with('0') {
            text.pop();
        }
        if text.ends_with('.') {
            text.push('0');
        }
        text
    } else {
        "0".to_string()
    }
}

fn escape_json_string(text: &str) -> String {
    let mut escaped = String::new();
    for ch in text.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            ch if ch.is_control() => {
                let _ = write!(escaped, "\\u{:04x}", ch as u32);
            }
            _ => escaped.push(ch),
        }
    }
    escaped
}
