use crate::format::{GspFile, PointRecord};
use crate::render::extract::build_scene;
use crate::render::functions::{BinaryOp, FunctionExpr, FunctionTerm, UnaryFunction};
use crate::render::geometry::darken;
use crate::render::scene::{Scene, ScenePointBinding, ScenePointConstraint, TextLabelBinding};
use serde::Serialize;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const VIEWER_CSS: &str = include_str!("html/viewer.css");
const VAN_JS: &str = include_str!("html/vendor/van-1.6.0.js");
const VIEWER_SCENE_JS: &str = include_str!("html/viewer_scene.js");
const VIEWER_RENDER_JS: &str = include_str!("html/viewer_render.js");
const VIEWER_DRAG_JS: &str = include_str!("html/viewer_drag.js");
const VIEWER_JS: &str = include_str!("html/viewer.js");

pub fn render_points_to_html(
    file: &GspFile,
    output_path: &Path,
    width: u32,
    height: u32,
) -> Result<(), String> {
    if !matches!(
        output_path.extension().and_then(|ext| ext.to_str()),
        Some("html") | Some("HTML") | Some("htm") | Some("HTM")
    ) {
        return Err(format!(
            "html output path must end with .html or .htm: {}",
            output_path.display()
        ));
    }

    let scene = build_scene(file);
    let html = build_standalone_html(&scene, width, height);

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "failed to create html output directory {}: {error}",
                parent.display()
            )
        })?;
    }

    fs::write(output_path, html)
        .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    Ok(())
}

fn build_standalone_html(scene: &Scene, width: u32, height: u32) -> String {
    let mut html = String::new();
    let scene_json = scene_to_json(scene, width, height);
    let van_js = van_runtime_to_global();
    let viewer_modules_js = format!("{VIEWER_SCENE_JS}\n{VIEWER_RENDER_JS}\n{VIEWER_DRAG_JS}");
    let frame_width = width + 40;
    let shape_count =
        scene.lines.len() + scene.polygons.len() + scene.circles.len() + scene.labels.len();
    let _ = write!(
        html,
        r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>gsp-rs export</title>
  <style>
    :root {{
      --frame-width: {frame_width}px;
    }}
{embedded_css}
  </style>
</head>
<body>
  <main>
    <div class="frame">
      <div class="toolbar">
        <div class="controls">
          <button id="reset-view" type="button">Reset View</button>
          <div id="parameter-controls"></div>
        </div>
        <span class="hint">Drag a point to edit, drag empty space to pan, wheel to zoom</span>
      </div>
      <canvas id="view" width="{width}" height="{height}"></canvas>
      <div class="meta">
        <span>Generated by gsp-rs</span>
        <span>{shape_count} shapes</span>
        <div class="right">
          <span id="coord-readout">x -, y -</span>
          <span id="zoom-readout">zoom 100%</span>
        </div>
      </div>
    </div>
  </main>
  <script id="scene-data" type="application/json">{scene_json}</script>
  <script>
{embedded_van_js}
  </script>
  <script>
{embedded_viewer_modules_js}
  </script>
  <script>
{embedded_js}
  </script>
</body>
</html>
"#,
        width = width,
        height = height,
        frame_width = frame_width,
        shape_count = shape_count,
        scene_json = scene_json,
        embedded_css = indent_asset(VIEWER_CSS, 4),
        embedded_van_js = indent_asset(&van_js, 4),
        embedded_viewer_modules_js = indent_asset(&viewer_modules_js, 4),
        embedded_js = indent_asset(VIEWER_JS, 4),
    );
    html
}

fn van_runtime_to_global() -> String {
    VAN_JS.replacen("export default {", "window.van = {", 1)
}

fn indent_asset(asset: &str, spaces: usize) -> String {
    let indent = " ".repeat(spaces);
    asset
        .lines()
        .map(|line| format!("{indent}{line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn scene_to_json(scene: &Scene, width: u32, height: u32) -> String {
    serde_json::to_string(&SceneJson::from_scene(scene, width, height))
        .expect("scene JSON serialization should succeed")
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct SceneJson {
    width: u32,
    height: u32,
    graph_mode: bool,
    pi_mode: bool,
    saved_viewport: bool,
    y_up: bool,
    bounds: BoundsJson,
    origin: Option<PointJson>,
    lines: Vec<LineJson>,
    polygons: Vec<PolygonJson>,
    circles: Vec<CircleJson>,
    labels: Vec<LabelJson>,
    points: Vec<ScenePointJson>,
    parameters: Vec<ParameterJson>,
    functions: Vec<FunctionJson>,
}

impl SceneJson {
    fn from_scene(scene: &Scene, width: u32, height: u32) -> Self {
        Self {
            width,
            height,
            graph_mode: scene.graph_mode,
            pi_mode: scene.pi_mode,
            saved_viewport: scene.saved_viewport,
            y_up: scene.y_up,
            bounds: BoundsJson::from_scene(scene),
            origin: scene.origin.as_ref().map(PointJson::from_point),
            lines: scene.lines.iter().map(LineJson::from_line).collect(),
            polygons: scene
                .polygons
                .iter()
                .map(PolygonJson::from_polygon)
                .collect(),
            circles: scene.circles.iter().map(CircleJson::from_circle).collect(),
            labels: scene.labels.iter().map(LabelJson::from_label).collect(),
            points: scene
                .points
                .iter()
                .map(ScenePointJson::from_scene_point)
                .collect(),
            parameters: scene
                .parameters
                .iter()
                .map(ParameterJson::from_parameter)
                .collect(),
            functions: scene
                .functions
                .iter()
                .map(FunctionJson::from_function)
                .collect(),
        }
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct BoundsJson {
    min_x: f64,
    max_x: f64,
    min_y: f64,
    max_y: f64,
}

impl BoundsJson {
    fn from_scene(scene: &Scene) -> Self {
        Self {
            min_x: scene.bounds.min_x,
            max_x: scene.bounds.max_x,
            min_y: scene.bounds.min_y,
            max_y: scene.bounds.max_y,
        }
    }
}

#[derive(Serialize)]
struct PointJson {
    x: f64,
    y: f64,
}

impl PointJson {
    fn from_point(point: &PointRecord) -> Self {
        Self {
            x: point.x,
            y: point.y,
        }
    }
}

#[derive(Serialize)]
struct LineJson {
    points: Vec<PointJson>,
    color: [u8; 4],
    dashed: bool,
}

impl LineJson {
    fn from_line(line: &crate::render::scene::LineShape) -> Self {
        Self {
            points: line.points.iter().map(PointJson::from_point).collect(),
            color: line.color,
            dashed: line.dashed,
        }
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct PolygonJson {
    points: Vec<PointJson>,
    color: [u8; 4],
    outline_color: [u8; 4],
}

impl PolygonJson {
    fn from_polygon(polygon: &crate::render::scene::PolygonShape) -> Self {
        Self {
            points: polygon.points.iter().map(PointJson::from_point).collect(),
            color: polygon.color,
            outline_color: darken(polygon.color, 80),
        }
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct CircleJson {
    center: PointJson,
    radius_point: PointJson,
    color: [u8; 4],
}

impl CircleJson {
    fn from_circle(circle: &crate::render::scene::SceneCircle) -> Self {
        Self {
            center: PointJson::from_point(&circle.center),
            radius_point: PointJson::from_point(&circle.radius_point),
            color: circle.color,
        }
    }
}

#[derive(Serialize)]
struct LabelJson {
    anchor: PointJson,
    text: String,
    color: [u8; 4],
    binding: Option<LabelBindingJson>,
    #[serde(rename = "screenSpace")]
    screen_space: bool,
}

impl LabelJson {
    fn from_label(label: &crate::render::scene::TextLabel) -> Self {
        Self {
            anchor: PointJson::from_point(&label.anchor),
            text: label.text.clone(),
            color: label.color,
            binding: label.binding.as_ref().map(LabelBindingJson::from_binding),
            screen_space: label.screen_space,
        }
    }
}

#[derive(Serialize)]
#[serde(tag = "kind")]
enum LabelBindingJson {
    #[serde(rename = "parameter-value")]
    ParameterValue { name: String },
    #[serde(rename = "expression-value")]
    ExpressionValue {
        #[serde(rename = "parameterName")]
        parameter_name: String,
        #[serde(rename = "exprLabel")]
        expr_label: String,
        expr: FunctionExprJson,
    },
    #[serde(rename = "polygon-boundary-parameter")]
    PolygonBoundaryParameter {
        #[serde(rename = "pointIndex")]
        point_index: usize,
        #[serde(rename = "pointName")]
        point_name: String,
        #[serde(rename = "polygonName")]
        polygon_name: String,
    },
    #[serde(rename = "segment-parameter")]
    SegmentParameter {
        #[serde(rename = "pointIndex")]
        point_index: usize,
        #[serde(rename = "pointName")]
        point_name: String,
        #[serde(rename = "segmentName")]
        segment_name: String,
    },
    #[serde(rename = "circle-parameter")]
    CircleParameter {
        #[serde(rename = "pointIndex")]
        point_index: usize,
        #[serde(rename = "pointName")]
        point_name: String,
        #[serde(rename = "circleName")]
        circle_name: String,
    },
}

impl LabelBindingJson {
    fn from_binding(binding: &TextLabelBinding) -> Self {
        match binding {
            TextLabelBinding::ParameterValue { name } => {
                Self::ParameterValue { name: name.clone() }
            }
            TextLabelBinding::ExpressionValue {
                parameter_name,
                expr_label,
                expr,
            } => Self::ExpressionValue {
                parameter_name: parameter_name.clone(),
                expr_label: expr_label.clone(),
                expr: FunctionExprJson::from_expr(expr),
            },
            TextLabelBinding::PolygonBoundaryParameter {
                point_index,
                point_name,
                polygon_name,
            } => Self::PolygonBoundaryParameter {
                point_index: *point_index,
                point_name: point_name.clone(),
                polygon_name: polygon_name.clone(),
            },
            TextLabelBinding::SegmentParameter {
                point_index,
                point_name,
                segment_name,
            } => Self::SegmentParameter {
                point_index: *point_index,
                point_name: point_name.clone(),
                segment_name: segment_name.clone(),
            },
            TextLabelBinding::CircleParameter {
                point_index,
                point_name,
                circle_name,
            } => Self::CircleParameter {
                point_index: *point_index,
                point_name: point_name.clone(),
                circle_name: circle_name.clone(),
            },
        }
    }
}

#[derive(Serialize)]
struct ScenePointJson {
    x: f64,
    y: f64,
    constraint: Option<PointConstraintJson>,
    binding: Option<PointBindingJson>,
}

impl ScenePointJson {
    fn from_scene_point(point: &crate::render::scene::ScenePoint) -> Self {
        Self {
            x: point.position.x,
            y: point.position.y,
            constraint: PointConstraintJson::from_constraint(&point.constraint),
            binding: point.binding.as_ref().map(PointBindingJson::from_binding),
        }
    }
}

#[derive(Serialize)]
#[serde(tag = "kind")]
enum PointBindingJson {
    #[serde(rename = "parameter")]
    Parameter { name: String },
    #[serde(rename = "derived-parameter")]
    DerivedParameter {
        #[serde(rename = "sourceIndex")]
        source_index: usize,
    },
    #[serde(rename = "rotate")]
    Rotate {
        #[serde(rename = "sourceIndex")]
        source_index: usize,
        #[serde(rename = "centerIndex")]
        center_index: usize,
        #[serde(rename = "angleDegrees")]
        angle_degrees: f64,
    },
    #[serde(rename = "scale")]
    Scale {
        #[serde(rename = "sourceIndex")]
        source_index: usize,
        #[serde(rename = "centerIndex")]
        center_index: usize,
        factor: f64,
    },
    #[serde(rename = "coordinate")]
    Coordinate {
        name: String,
        expr: FunctionExprJson,
    },
}

impl PointBindingJson {
    fn from_binding(binding: &ScenePointBinding) -> Self {
        match binding {
            ScenePointBinding::Parameter { name } => Self::Parameter { name: name.clone() },
            ScenePointBinding::DerivedParameter { source_index } => Self::DerivedParameter {
                source_index: *source_index,
            },
            ScenePointBinding::Rotate {
                source_index,
                center_index,
                angle_degrees,
            } => Self::Rotate {
                source_index: *source_index,
                center_index: *center_index,
                angle_degrees: *angle_degrees,
            },
            ScenePointBinding::Scale {
                source_index,
                center_index,
                factor,
            } => Self::Scale {
                source_index: *source_index,
                center_index: *center_index,
                factor: *factor,
            },
            ScenePointBinding::Coordinate { name, expr } => Self::Coordinate {
                name: name.clone(),
                expr: FunctionExprJson::from_expr(expr),
            },
        }
    }
}

#[derive(Serialize)]
#[serde(tag = "kind")]
enum PointConstraintJson {
    #[serde(rename = "offset")]
    Offset {
        #[serde(rename = "originIndex")]
        origin_index: usize,
        dx: f64,
        dy: f64,
    },
    #[serde(rename = "segment")]
    Segment {
        #[serde(rename = "startIndex")]
        start_index: usize,
        #[serde(rename = "endIndex")]
        end_index: usize,
        t: f64,
    },
    #[serde(rename = "polyline")]
    Polyline {
        #[serde(rename = "functionKey")]
        function_key: usize,
        points: Vec<PointJson>,
        #[serde(rename = "segmentIndex")]
        segment_index: usize,
        t: f64,
    },
    #[serde(rename = "polygon-boundary")]
    PolygonBoundary {
        #[serde(rename = "vertexIndices")]
        vertex_indices: Vec<usize>,
        #[serde(rename = "edgeIndex")]
        edge_index: usize,
        t: f64,
    },
    #[serde(rename = "circle")]
    Circle {
        #[serde(rename = "centerIndex")]
        center_index: usize,
        #[serde(rename = "radiusIndex")]
        radius_index: usize,
        #[serde(rename = "unitX")]
        unit_x: f64,
        #[serde(rename = "unitY")]
        unit_y: f64,
    },
}

impl PointConstraintJson {
    fn from_constraint(constraint: &ScenePointConstraint) -> Option<Self> {
        match constraint {
            ScenePointConstraint::Free => None,
            ScenePointConstraint::Offset {
                origin_index,
                dx,
                dy,
            } => Some(Self::Offset {
                origin_index: *origin_index,
                dx: *dx,
                dy: *dy,
            }),
            ScenePointConstraint::OnSegment {
                start_index,
                end_index,
                t,
            } => Some(Self::Segment {
                start_index: *start_index,
                end_index: *end_index,
                t: *t,
            }),
            ScenePointConstraint::OnPolyline {
                function_key,
                points,
                segment_index,
                t,
            } => Some(Self::Polyline {
                function_key: *function_key,
                points: points.iter().map(PointJson::from_point).collect(),
                segment_index: *segment_index,
                t: *t,
            }),
            ScenePointConstraint::OnPolygonBoundary {
                vertex_indices,
                edge_index,
                t,
            } => Some(Self::PolygonBoundary {
                vertex_indices: vertex_indices.clone(),
                edge_index: *edge_index,
                t: *t,
            }),
            ScenePointConstraint::OnCircle {
                center_index,
                radius_index,
                unit_x,
                unit_y,
            } => Some(Self::Circle {
                center_index: *center_index,
                radius_index: *radius_index,
                unit_x: *unit_x,
                unit_y: *unit_y,
            }),
        }
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ParameterJson {
    name: String,
    value: f64,
    label_index: Option<usize>,
}

impl ParameterJson {
    fn from_parameter(parameter: &crate::render::scene::SceneParameter) -> Self {
        Self {
            name: parameter.name.clone(),
            value: parameter.value,
            label_index: parameter.label_index,
        }
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct FunctionJson {
    key: usize,
    name: String,
    derivative: bool,
    domain: DomainJson,
    line_index: Option<usize>,
    label_index: usize,
    constrained_point_indices: Vec<usize>,
    expr: FunctionExprJson,
}

impl FunctionJson {
    fn from_function(function_def: &crate::render::scene::SceneFunction) -> Self {
        Self {
            key: function_def.key,
            name: function_def.name.clone(),
            derivative: function_def.derivative,
            domain: DomainJson {
                x_min: function_def.domain.x_min,
                x_max: function_def.domain.x_max,
                sample_count: function_def.domain.sample_count,
            },
            line_index: function_def.line_index,
            label_index: function_def.label_index,
            constrained_point_indices: function_def.constrained_point_indices.clone(),
            expr: FunctionExprJson::from_expr(&function_def.expr),
        }
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct DomainJson {
    x_min: f64,
    x_max: f64,
    sample_count: usize,
}

#[derive(Serialize)]
#[serde(tag = "kind")]
enum FunctionExprJson {
    #[serde(rename = "constant")]
    Constant { value: f64 },
    #[serde(rename = "identity")]
    Identity,
    #[serde(rename = "parsed")]
    Parsed {
        head: FunctionTermJson,
        tail: Vec<ExprTailJson>,
    },
}

impl FunctionExprJson {
    fn from_expr(expr: &FunctionExpr) -> Self {
        match expr {
            FunctionExpr::Constant(value) => Self::Constant { value: *value },
            FunctionExpr::Identity => Self::Identity,
            FunctionExpr::SinIdentity => Self::Parsed {
                head: FunctionTermJson::UnaryX { op: "sin" },
                tail: Vec::new(),
            },
            FunctionExpr::CosIdentityPlus(offset) => Self::Parsed {
                head: FunctionTermJson::UnaryX { op: "cos" },
                tail: vec![ExprTailJson {
                    op: "add",
                    term: FunctionTermJson::Constant { value: *offset },
                }],
            },
            FunctionExpr::TanIdentityMinus(offset) => Self::Parsed {
                head: FunctionTermJson::UnaryX { op: "tan" },
                tail: vec![ExprTailJson {
                    op: "sub",
                    term: FunctionTermJson::Constant { value: *offset },
                }],
            },
            FunctionExpr::Parsed(parsed) => Self::Parsed {
                head: FunctionTermJson::from_term(&parsed.head),
                tail: parsed
                    .tail
                    .iter()
                    .map(|(op, term)| ExprTailJson {
                        op: binary_op_name(*op),
                        term: FunctionTermJson::from_term(term),
                    })
                    .collect(),
            },
        }
    }
}

#[derive(Serialize)]
struct ExprTailJson {
    op: &'static str,
    term: FunctionTermJson,
}

#[derive(Serialize)]
#[serde(tag = "kind")]
enum FunctionTermJson {
    #[serde(rename = "variable")]
    Variable,
    #[serde(rename = "constant")]
    Constant { value: f64 },
    #[serde(rename = "parameter")]
    Parameter { name: String, value: f64 },
    #[serde(rename = "unary_x")]
    UnaryX { op: &'static str },
    #[serde(rename = "product")]
    Product {
        left: Box<FunctionTermJson>,
        right: Box<FunctionTermJson>,
    },
}

impl FunctionTermJson {
    fn from_term(term: &FunctionTerm) -> Self {
        match term {
            FunctionTerm::Variable => Self::Variable,
            FunctionTerm::Constant(value) => Self::Constant { value: *value },
            FunctionTerm::Parameter(name, value) => Self::Parameter {
                name: name.clone(),
                value: *value,
            },
            FunctionTerm::UnaryX(op) => Self::UnaryX {
                op: unary_function_name(*op),
            },
            FunctionTerm::Product(left, right) => Self::Product {
                left: Box::new(Self::from_term(left)),
                right: Box::new(Self::from_term(right)),
            },
        }
    }
}

fn binary_op_name(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "add",
        BinaryOp::Sub => "sub",
        BinaryOp::Mul => "mul",
    }
}

fn unary_function_name(op: UnaryFunction) -> &'static str {
    match op {
        UnaryFunction::Sin => "sin",
        UnaryFunction::Cos => "cos",
        UnaryFunction::Tan => "tan",
        UnaryFunction::Abs => "abs",
        UnaryFunction::Sqrt => "sqrt",
        UnaryFunction::Ln => "ln",
        UnaryFunction::Log10 => "log10",
        UnaryFunction::Sign => "sign",
        UnaryFunction::Round => "round",
        UnaryFunction::Trunc => "trunc",
    }
}
