use crate::export::html::{render_scene_json, render_standalone_html_document, write_standalone_html};
use crate::gsp;
use crate::runtime::build_scene;
use std::fs;
use std::path::Path;

pub fn compile_file_to_html(
    gsp_path: &Path,
    html_path: &Path,
    width: u32,
    height: u32,
) -> Result<(), String> {
    let data = fs::read(gsp_path)
        .map_err(|error| format!("failed to read {}: {error}", gsp_path.display()))?;
    compile_bytes_to_html_file(&data, html_path, width, height)
}

pub fn compile_file_to_scene_json(
    gsp_path: &Path,
    width: u32,
    height: u32,
) -> Result<String, String> {
    let data = fs::read(gsp_path)
        .map_err(|error| format!("failed to read {}: {error}", gsp_path.display()))?;
    compile_bytes_to_scene_json(&data, width, height)
}

pub fn compile_bytes_to_html_file(
    data: &[u8],
    html_path: &Path,
    width: u32,
    height: u32,
) -> Result<(), String> {
    let html = compile_bytes_to_html_document(data, width, height)?;
    write_standalone_html(html_path, &html)
}

pub fn compile_bytes_to_html_document(
    data: &[u8],
    width: u32,
    height: u32,
) -> Result<String, String> {
    let file = gsp::parse(data)?;
    let scene = build_scene(&file);
    Ok(render_standalone_html_document(&scene, width, height))
}

pub fn compile_bytes_to_scene_json(
    data: &[u8],
    width: u32,
    height: u32,
) -> Result<String, String> {
    let file = gsp::parse(data)?;
    let scene = build_scene(&file);
    Ok(render_scene_json(&scene, width, height, true))
}

#[cfg(test)]
mod tests {
    use super::{compile_bytes_to_html_document, compile_bytes_to_scene_json};

    #[test]
    fn compiles_fixture_into_standalone_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/point.gsp"),
            800,
            600,
        )
        .expect("fixture should compile");

        assert!(html.contains("<!doctype html>"));
        assert!(html.contains("<canvas id=\"view\""));
        assert!(html.contains("Generated by gsp-rs"));
        assert!(html.contains("application/json"));
        assert!(html.contains("toggle-debug"));
        assert!(html.contains("window.gspDebug"));
    }

    #[test]
    fn exports_scene_json_for_console_debugging() {
        let scene_json =
            compile_bytes_to_scene_json(include_bytes!("../tests/fixtures/gsp/static/point.gsp"), 800, 600)
                .expect("fixture should compile");

        assert!(scene_json.contains("\n  \"width\": 800,"));
        assert!(scene_json.contains("\"points\": ["));
    }

    #[test]
    fn exports_segment_intersection_fixture_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/insection/segment_insection.gsp"),
            800,
            600,
        )
        .expect("segment intersection fixture should compile");

        assert!(html.contains("\"x\":416.3160761196899"));
        assert!(html.contains("\"y\":321.2222079835971"));
        assert!(html.contains("\"kind\":\"line-intersection\""));
    }

    #[test]
    fn exports_point_iteration_metadata_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/简单迭代/原象点初象点深度5迭代.gsp"),
            800,
            600,
        )
        .expect("iteration fixture should compile");

        assert!(html.contains("\"pointIterations\":["));
        assert!(html.contains("\"parameterName\":\"n\""));
    }

    #[test]
    fn exports_non_graph_iteration_parameters_and_expression_bindings_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!(
                "../tests/fixtures/gsp/static/简单迭代/原象点和参数初象点和数值深度5迭代.gsp"
            ),
            800,
            600,
        )
        .expect("non-graph iteration fixture should compile");

        assert!(html.contains("\"name\":\"n\""));
        assert!(html.contains("\"name\":\"a\""));
        assert!(html.contains("\"kind\":\"parameter-value\",\"name\":\"a\""));
        assert!(html.contains("\"kind\":\"point-expression-value\""));
        assert!(html.contains("\"parameterName\":\"a\""));
        assert!(html.contains("\"pointIndex\":1"));
        assert!(html.contains("\"kind\":\"expression-value\",\"parameterName\":\"a\""));
        assert!(html.contains("\"labelIterations\":["));
    }

    #[test]
    fn exports_default_depth_iteration_metadata_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/简单迭代/原象点初象点默认深度3迭代.gsp"),
            800,
            600,
        )
        .expect("default iteration fixture should compile");

        assert!(html.contains("\"pointIterations\":["));
        assert!(html.contains("\"depth\":3"));
    }

    #[test]
    fn exports_default_depth_non_graph_iteration_fixture_metadata() {
        let html = compile_bytes_to_html_document(
            include_bytes!(
                "../tests/fixtures/gsp/static/简单迭代/原象点和参数初象点和数值默认深度迭代.gsp"
            ),
            800,
            600,
        )
        .expect("default non-graph iteration fixture should compile");

        assert!(html.contains("\"name\":\"a\""));
        assert!(html.contains("\"pointIterations\":["));
        assert!(html.contains("\"labelIterations\":["));
        assert!(html.contains("\"depth\":3"));
        assert!(!html.contains("\"depthParameterName\":\"B\""));
    }

    #[test]
    fn exports_carried_polygon_iteration_metadata_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!(
                "../tests/fixtures/gsp/static/简单迭代/原象点初象携带多边形双映射深度4迭代.gsp"
            ),
            800,
            600,
        )
        .expect("carried polygon iteration fixture should compile");

        assert!(html.contains("\"lineIterations\":[]"));
        assert!(html.contains("\"polygonIterations\":["));
        assert!(html.contains("\"parameterName\":\"n\""));
        assert!(html.contains("\"vertexIndices\":[0,2,1]"));
        assert!(html.contains("\"secondaryDx\":37.79527559055118"));
    }

    #[test]
    fn exports_perpendicular_line_binding_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/perpendicular.gsp"),
            800,
            600,
        )
        .expect("perpendicular fixture should compile");

        assert!(html.contains("\"kind\":\"perpendicular-line\""));
        assert!(html.contains("\"throughIndex\":1"));
        assert!(html.contains("\"lineStartIndex\":0"));
        assert!(html.contains("\"lineEndIndex\":1"));
    }

    #[test]
    fn exports_parallel_line_binding_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/parallel.gsp"),
            800,
            600,
        )
        .expect("parallel fixture should compile");

        assert!(html.contains("\"kind\":\"parallel-line\""));
        assert!(html.contains("\"throughIndex\":2"));
        assert!(html.contains("\"lineStartIndex\":0"));
        assert!(html.contains("\"lineEndIndex\":1"));
    }

    #[test]
    fn exports_angle_bisector_ray_binding_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/bisector.gsp"),
            800,
            600,
        )
        .expect("bisector fixture should compile");

        assert!(html.contains("\"kind\":\"angle-bisector-ray\""));
        assert!(html.contains("\"startIndex\":0"));
        assert!(html.contains("\"vertexIndex\":1"));
        assert!(html.contains("\"endIndex\":2"));
    }

    #[test]
    fn exports_perpendicular_bisector_fixture_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/中垂线.gsp"),
            800,
            600,
        )
        .expect("perpendicular bisector fixture should compile");

        assert!(html.contains("\"kind\":\"perpendicular-line\""));
        assert!(html.contains("\"throughIndex\":2"));
        assert!(html.contains(
            "\"constraint\":{\"kind\":\"segment\",\"startIndex\":0,\"endIndex\":1,\"t\":0.5}"
        ));
    }

    #[test]
    fn exports_nested_perpendicular_parallel_marker_bindings_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/pert_vert.gsp"),
            800,
            600,
        )
        .expect("pert_vert fixture should compile");

        assert!(html.contains("\"kind\":\"perpendicular-line\",\"throughIndex\":3"));
        assert!(html.contains("\"kind\":\"perpendicular-line\",\"throughIndex\":1"));
        assert!(html.contains("\"kind\":\"parallel-line\",\"throughIndex\":1"));
        assert!(html.contains("\"lineIndex\":1"));
    }

    #[test]
    fn exports_three_point_arc_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/three_point_arc.gsp"),
            800,
            600,
        )
        .expect("three-point arc fixture should compile");

        assert!(html.contains("\"arcs\":["));
        assert!(html.contains("\"color\":[0,128,0,255]"));
        assert!(html.contains("\"points\":[{\"x\":323.0,\"y\":217.0}"));
    }

    #[test]
    fn exports_three_point_arc_point_constraint_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/three_point_arc_point.gsp"),
            800,
            600,
        )
        .expect("three-point arc point fixture should compile");

        assert!(html.contains("\"kind\":\"arc\""));
        assert!(html.contains("\"startIndex\":0"));
        assert!(html.contains("\"midIndex\":1"));
        assert!(html.contains("\"endIndex\":2"));
    }

    #[test]
    fn exports_arc_on_circle_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/arc_on_circle.gsp"),
            800,
            600,
        )
        .expect("arc-on-circle fixture should compile");

        assert!(html.contains("\"arcs\":["));
        assert!(html.contains("\"dashed\":true"));
        assert!(html.contains("\"counterclockwise\":true"));
        assert!(html.contains("\"points\":[{\"x\":411.18946322164174"));
    }

    #[test]
    fn exports_circle_center_radius_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/circle_center_radius.gsp"),
            800,
            600,
        )
        .expect("circle-center-radius fixture should compile");

        assert!(html.contains("\"circles\":[{\"center\":{\"x\":348.0,\"y\":177.0}"));
        assert!(html.contains("\"kind\":\"segment-radius-circle\""));
        assert!(html.contains(
            "\"lines\":[{\"points\":[{\"x\":318.0,\"y\":391.0},{\"x\":403.0,\"y\":390.0}]"
        ));
    }

    #[test]
    fn exports_multiline_text_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/多行文本.gsp"),
            800,
            600,
        )
        .expect("multiline text fixture should compile");

        assert!(html.contains(
            "\"text\":\"线段中垂线\\n垂线\\n平行线\\n直角三角形\\n点的轨迹\\n圆上的弧\\n过三点的弧\""
        ));
    }

    #[test]
    fn exports_angle_sign_fixture_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/angle-sign.gsp"),
            800,
            600,
        )
        .expect("angle-sign fixture should compile");

        assert!(html.contains("\"labels\":[{\"anchor\":{\"x\":774.0,\"y\":485.0},\"text\":\"A\""));
        assert!(html.contains("\"kind\":\"rotate\",\"sourceIndex\":1,\"centerIndex\":0,\"angleDegrees\":90.0"));
        assert!(html.contains("\"kind\":\"scale\",\"sourceIndex\":2,\"centerIndex\":0,\"factor\":1.5"));
        assert!(html.contains("\"kind\":\"segment\",\"startIndex\":3,\"endIndex\":0"));
        assert!(html.contains("\"points\":[{\"x\":786.125,\"y\":480.0},{\"x\":786.125,\"y\":459.875},{\"x\":766.0,\"y\":459.875}]"));
    }

    #[test]
    fn exports_hidden_point_fixture_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/point_hidden.gsp"),
            800,
            600,
        )
        .expect("hidden-point fixture should compile");

        assert!(html.contains("\"points\":[{\"x\":323.0,\"y\":217.0,\"visible\":false"));
        assert!(html.contains("\"lines\":[]"));
    }

    #[test]
    fn exports_translated_triangle_segments_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/两个三角形标记全等.gsp"),
            800,
            600,
        )
        .expect("congruent triangle fixture should compile");

        assert!(html.contains("\"kind\":\"translate-line\""));
        assert!(html.contains("\"kind\":\"angle-marker\""));
        assert!(html.contains("\"kind\":\"segment-marker\""));
        assert!(html.contains("\"vectorStartIndex\":0,\"vectorEndIndex\":3"));
        assert!(html.contains("\"text\":\"B'\""));
        assert!(html.contains("\"text\":\"C'\""));
    }
}
