use crate::export::html::{render_standalone_html_document, write_standalone_html};
use crate::gsp;
use crate::runtime::build_scene;
use std::fs;
use std::path::Path;

pub fn compile_file_to_html(
    gsp_path: &Path,
    html_path: &Path,
    width: u32,
    height: u32,
) -> Result<(), String> {
    let data = fs::read(gsp_path)
        .map_err(|error| format!("failed to read {}: {error}", gsp_path.display()))?;
    compile_bytes_to_html_file(&data, html_path, width, height)
}

pub fn compile_bytes_to_html_file(
    data: &[u8],
    html_path: &Path,
    width: u32,
    height: u32,
) -> Result<(), String> {
    let html = compile_bytes_to_html_document(data, width, height)?;
    write_standalone_html(html_path, &html)
}

pub fn compile_bytes_to_html_document(
    data: &[u8],
    width: u32,
    height: u32,
) -> Result<String, String> {
    let file = gsp::parse(data)?;
    let scene = build_scene(&file);
    Ok(render_standalone_html_document(&scene, width, height))
}

#[cfg(test)]
mod tests {
    use super::compile_bytes_to_html_document;

    #[test]
    fn compiles_fixture_into_standalone_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/point.gsp"),
            800,
            600,
        )
        .expect("fixture should compile");

        assert!(html.contains("<!doctype html>"));
        assert!(html.contains("<canvas id=\"view\""));
        assert!(html.contains("Generated by gsp-rs"));
        assert!(html.contains("application/json"));
    }

    #[test]
    fn exports_point_iteration_metadata_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/简单迭代/原象点初象点深度5迭代.gsp"),
            800,
            600,
        )
        .expect("iteration fixture should compile");

        assert!(html.contains("\"pointIterations\":["));
        assert!(html.contains("\"parameterName\":\"n\""));
    }

    #[test]
    fn exports_non_graph_iteration_parameters_and_expression_bindings_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!(
                "../tests/fixtures/gsp/static/简单迭代/原象点和参数初象点和数值深度5迭代.gsp"
            ),
            800,
            600,
        )
        .expect("non-graph iteration fixture should compile");

        assert!(html.contains("\"name\":\"n\""));
        assert!(html.contains("\"name\":\"a\""));
        assert!(html.contains("\"kind\":\"parameter-value\",\"name\":\"a\""));
        assert!(html.contains("\"kind\":\"point-expression-value\""));
        assert!(html.contains("\"parameterName\":\"a\""));
        assert!(html.contains("\"pointIndex\":1"));
        assert!(html.contains("\"kind\":\"expression-value\",\"parameterName\":\"a\""));
        assert!(html.contains("\"labelIterations\":["));
    }

    #[test]
    fn exports_default_depth_iteration_metadata_into_html() {
        let html = compile_bytes_to_html_document(
            include_bytes!("../tests/fixtures/gsp/static/简单迭代/原象点初象点默认深度3迭代.gsp"),
            800,
            600,
        )
        .expect("default iteration fixture should compile");

        assert!(html.contains("\"pointIterations\":["));
        assert!(html.contains("\"depth\":3"));
    }

    #[test]
    fn exports_default_depth_non_graph_iteration_fixture_metadata() {
        let html = compile_bytes_to_html_document(
            include_bytes!(
                "../tests/fixtures/gsp/static/简单迭代/原象点和参数初象点和数值默认深度迭代.gsp"
            ),
            800,
            600,
        )
        .expect("default non-graph iteration fixture should compile");

        assert!(html.contains("\"name\":\"a\""));
        assert!(html.contains("\"pointIterations\":["));
        assert!(html.contains("\"labelIterations\":["));
        assert!(html.contains("\"depth\":3"));
        assert!(!html.contains("\"depthParameterName\":\"B\""));
    }
}
