use std::{
    env, fs, io,
    path::{Path, PathBuf},
    process::Command,
};

use oxc_allocator::Allocator;
use oxc_codegen::{Codegen, CodegenOptions, CodegenReturn};
use oxc_data_structures::code_buffer::IndentChar;
use oxc_parser::Parser;
use oxc_semantic::SemanticBuilder;
use oxc_span::SourceType;
use oxc_transformer::{ESTarget, TransformOptions, Transformer};

pub const VIEWER_RUNTIME_FILE: &str = "viewer-runtime.js";
pub const RUNTIME_CORE_WASM_BASE64_FILE: &str = "runtime-core.wasm.b64";

const RUNTIME_SOURCES: &[&str] = &[
    "viewer_runtime_core",
    "viewer_geometry",
    "viewer_scene_basic",
    "viewer_scene_circular",
    "viewer_scene_trace",
    "viewer_scene_intersections",
    "viewer_render_basic",
    "viewer_render_images",
    "viewer_render_polygons",
    "viewer_render_circular",
    "viewer_render_labels",
    "viewer_render_tables",
    "viewer_render_hotspots",
    "viewer_overlay",
    "viewer_drag",
    "viewer_dynamics_expression",
    "viewer_dynamics_rich_text",
    "viewer_dynamics_parameters",
    "viewer_dynamics_iterations",
    "viewer_dynamics_dependency_graph",
    "viewer_dynamics",
    "viewer_app_document",
    "viewer_app_debug_graph",
    "viewer",
];

// Chrome 109 and Firefox 115 ESR are the final practical Windows 7 targets.
// Keep the embedded module on their conservative WebAssembly feature baseline.
const WIN7_WASM_RUSTFLAGS: &str = "-Ctarget-feature=+bulk-memory,+mutable-globals,+sign-ext,-extended-const,-multivalue,-nontrapping-fptoint,-reference-types,-relaxed-simd,-simd128,-tail-call";

#[derive(Debug, Clone)]
pub struct RuntimeAssetPaths {
    pub viewer_runtime_js: PathBuf,
    pub runtime_core_wasm_base64: PathBuf,
}

pub fn build_runtime_assets(
    repo_root: &Path,
    output_dir: &Path,
    wasm_target_dir: &Path,
) -> Result<RuntimeAssetPaths, Box<dyn std::error::Error>> {
    fs::create_dir_all(output_dir)?;
    fs::create_dir_all(wasm_target_dir)?;
    let runtime_core_wasm_base64 = build_runtime_core_wasm(repo_root, output_dir, wasm_target_dir)?;
    let viewer_runtime_js = write_runtime_bundle(repo_root, output_dir)?;
    Ok(RuntimeAssetPaths {
        viewer_runtime_js,
        runtime_core_wasm_base64,
    })
}

fn build_runtime_core_wasm(
    root: &Path,
    output_dir: &Path,
    wasm_target_dir: &Path,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let cargo = env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    run_command(
        Command::new(cargo)
            .env_remove("CARGO_ENCODED_RUSTFLAGS")
            .env_remove("CARGO_MAKEFLAGS")
            .env_remove("MAKEFLAGS")
            .env("RUSTFLAGS", WIN7_WASM_RUSTFLAGS)
            .args([
                "build",
                "-p",
                "gsp-runtime-core",
                "--target",
                "wasm32-unknown-unknown",
                "--profile",
                "wasm-release",
                "--target-dir",
            ])
            .arg(wasm_target_dir),
        root,
    )?;
    let wasm = fs::read(
        wasm_target_dir.join("wasm32-unknown-unknown/wasm-release/gsp_runtime_core.wasm"),
    )?;
    let output_path = output_dir.join(RUNTIME_CORE_WASM_BASE64_FILE);
    fs::write(&output_path, encode_base64(&wasm))?;
    Ok(output_path)
}

fn write_runtime_bundle(
    root: &Path,
    output_dir: &Path,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let output_path = output_dir.join(VIEWER_RUNTIME_FILE);
    let mut bundle = String::from(
        "// Generated by gsp-runtime-assets. Do not edit by hand.\n\
         // Source files live in src/html/runtime/*.ts.\n\n",
    );
    for source in RUNTIME_SOURCES {
        let source_path = root.join(format!("src/html/runtime/{source}.ts"));
        let source_js =
            transpile_typescript(&source_path)?.replace("import(\"./generated/", "import(\"./");
        bundle.push_str("// ---- ");
        bundle.push_str(source);
        bundle.push_str(".ts ----\n");
        bundle.push_str(source_js.trim_end());
        bundle.push_str("\n\n");
    }
    fs::write(&output_path, bundle)?;
    Ok(output_path)
}

fn transpile_typescript(path: &Path) -> Result<String, Box<dyn std::error::Error>> {
    let source = fs::read_to_string(path)?;
    let allocator = Allocator::default();
    let source_type = SourceType::from_path(path)?.with_typescript(true);
    let parser_return = Parser::new(&allocator, &source, source_type).parse();
    if !parser_return.errors.is_empty() {
        return Err(format!(
            "failed to parse {}: {} diagnostic(s)",
            path.display(),
            parser_return.errors.len(),
        )
        .into());
    }

    let mut program = parser_return.program;
    let semantic = SemanticBuilder::new()
        .with_excess_capacity(2.0)
        .with_enum_eval(true)
        .build(&program);
    if !semantic.errors.is_empty() {
        return Err(format!(
            "failed to analyze {}: {} diagnostic(s)",
            path.display(),
            semantic.errors.len(),
        )
        .into());
    }

    let transform_options = TransformOptions::from(ESTarget::ES2021);
    let transformed = Transformer::new(&allocator, path, &transform_options)
        .build_with_scoping(semantic.semantic.into_scoping(), &mut program);
    if !transformed.errors.is_empty() {
        return Err(format!(
            "failed to transform {}: {} diagnostic(s)",
            path.display(),
            transformed.errors.len(),
        )
        .into());
    }

    let options = CodegenOptions {
        minify: false,
        indent_char: IndentChar::Space,
        indent_width: 2,
        ..CodegenOptions::default()
    };
    let CodegenReturn { code, .. } = Codegen::new().with_options(options).build(&program);
    Ok(code)
}

fn encode_base64(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut encoded = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let first = chunk[0];
        let second = chunk.get(1).copied().unwrap_or(0);
        let third = chunk.get(2).copied().unwrap_or(0);
        encoded.push(ALPHABET[(first >> 2) as usize] as char);
        encoded.push(ALPHABET[(((first & 0x03) << 4) | (second >> 4)) as usize] as char);
        encoded.push(if chunk.len() > 1 {
            ALPHABET[(((second & 0x0f) << 2) | (third >> 6)) as usize] as char
        } else {
            '='
        });
        encoded.push(if chunk.len() > 2 {
            ALPHABET[(third & 0x3f) as usize] as char
        } else {
            '='
        });
    }
    encoded
}

fn run_command(command: &mut Command, cwd: impl AsRef<Path>) -> io::Result<()> {
    let status = command.current_dir(cwd).status()?;
    if status.success() {
        return Ok(());
    }
    Err(io::Error::other(format!(
        "command failed with status {status}: {command:?}. Ensure the wasm32-unknown-unknown Rust target is installed",
    )))
}

#[cfg(test)]
mod tests {
    use super::encode_base64;

    #[test]
    fn base64_encoder_handles_padding() {
        assert_eq!(encode_base64(b""), "");
        assert_eq!(encode_base64(b"f"), "Zg==");
        assert_eq!(encode_base64(b"fo"), "Zm8=");
        assert_eq!(encode_base64(b"foo"), "Zm9v");
    }
}
